<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['compensate_record'] = array(
    'columns' => array(
        'id'   => array(
            'type'     => 'int unsigned',
            'extra'    => 'auto_increment',
            'pkey'     => true,
            'editable' => false,
            'label'    => '自增ID',
        ),
        'compensate_bn'  => array(
            'type'          => 'varchar(255)',
            'label'         => '赔付单号',
            'default'       => '',
            'is_title'      => true,
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 10,
            'searchtype'    => 'nequal',
            'filtertype'    => 'normal',
            'filterdefault' => true,
        ),
        'compensate_keyid'  => array(
            'type'          => 'varchar(255)',
            'label'         => '赔付子单号',
            'default'       => '',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 20,
        ),
        'type'  => array(
            'type'          => 'varchar(255)',
            'label'         => '赔付类型',
            'default'       => '',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 30,
        ),
        'compensate_type'  => array(
            'type'          => 'varchar(255)',
            'label'         => '赔付子类型',
            'default'       => '',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 40,
        ),
        'order_bn'  => array(
            'type'          => 'varchar(255)',
            'label'         => '订单号',
            'default'       => '',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 50,
            'searchtype'    => 'nequal',
            'filtertype'    => 'normal',
            'filterdefault' => true,
        ),
        'in_billcenter'  => array(
            'type'          => [
                'none' => '未写入',
                'succ' => '写入成功',
                'fail' => '写入失败',
            ],
            'label'         => '写入售后单',
            'default'       => 'none',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 55,
        ),
        'in_billcenter_msg'  => array(
            'type'          => 'varchar(255)',
            'label'         => '写入售后单信息',
            'default'       => '',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 56,
        ),
        'op_name'  => array(
            'type'          => 'varchar(64)',
            'label'         => '导入人',
            'default'       => '',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 56,
        ),
        'shop_id'  => array(
            'type'          => 'table:shop@ome',
            'label'         => '店铺名称',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 60,
        ),
        'order_type'  => array(
            'type'          => 'varchar(255)',
            'label'         => '订单类型',
            'default'       => '',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 70,
        ),
        'shouldpay'  => array(
            'type'          => 'money',
            'label'         => '应赔付金额',
            'default'       => 0,
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 80,
        ),
        'compensateamount'  => array(
            'type'          => 'money',
            'label'         => '赔付金额',
            'default'       => 0,
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 90,
        ),
        'check_status'  => array(
            'type'          => [
                '0' => '待审核',
                '1' => '审核通过',
                '2' => '审核不通过',
                '3' => '同意关单'
            ],
            'label'         => '审核状态',
            'default'       => '0',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 100,
        ),
        'reason'  => array(
            'type'          => 'varchar(255)',
            'label'         => '赔付原因',
            'default'       => '',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 110,
        ),
        'accountability'  => array(
            'type'          => 'varchar(255)',
            'label'         => '责任归属',
            'default'       => '',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 120,
        ),
        'can_second_appeal'  => array(
            'type'          => [
                '0' => '可以',
                '1' => '不可以',
            ],
            'label'         => '二次申诉',
            'default'       => '0',
            'in_list'       => true,
            'default_in_list' => true,
            'order'         => 130,
        ),
        'outer_created'       => array(
            'type'            => 'char(19)',
            'label'           => '外部创建时间',
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 140,
        ),
        'outer_modified'       => array(
            'type'            => 'char(19)',
            'label'           => '外部更新时间',
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 150,
        ),
        'at_time'       => array(
            'type'            => 'TIMESTAMP',
            'label'           => '创建时间',
            'default'         => 'CURRENT_TIMESTAMP',
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 1000,
        ),
        'up_time'       => array(
            'type'            => 'TIMESTAMP',
            'label'           => '更新时间',
            'default'         => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 1010,
        ),
    ),
    'index'   => array(
        'idx_compensate_bn_shop_id'       => array('columns' => array('compensate_bn','shop_id'), 'prefix'=>'unique'),
        'idx_order_bn'      => array('columns' => array('order_bn')),
        'idx_at_time'       => array('columns' => array('at_time')),
        'idx_up_time'       => array('columns' => array('up_time')),
    ),
    'engine'  => 'innodb',
    'commit'  => '赔付单记录',
    'version' => 'Rev: 41996 $',
);