<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['delivery_bill'] = array (
    'columns' => array (
        'log_id' => array (
            'type' => 'int unsigned',
            'required' => true,
            'pkey' => true,
            'editable' => false,
            'extra' => 'auto_increment',
        ),
        'delivery_id' => array (
            'type' => 'int unsigned',
            'required' => true,
            'editable' => false,
            'label' => '发货单号',
            'width' =>140,
            'in_list' => true,
        ),
        'delivery_bn' => array (
            'type' => 'varchar(32)',
            'required' => true,
            'label' => '发货单号',
            'editable' => false,
            'width' =>140,
            'searchtype' => 'nequal',
            'filtertype' => 'textarea',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 12,
        ),
        'logi_code' => array (
            'type' => 'varchar(20)',
            'label' => '物流编码',
            'editable' => false,
            'width' =>110,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 40,
        ),
        'logi_no' => array (
            'type' => 'varchar(50)',
            'label' => '物流单号',
            'editable' => false,
            'width' =>110,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 41,
        ),
        'status' => array (
            'type' => array (
                '0' => '未发货',
                '1' => '已发货',
                '2' => '已取消',
                '3' => '已接受',
                '4' => '已签收',
                '5' => '已支付',
            ),
            'default' => '0',
            'width' => 90,
            'required' => true,
            'editable' => false,
            'label' => '状态',
            'filtertype' => 'normal',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 20,
        ),
        'weight' => array (
            'type' => 'money',
            'editable' => false,
            'label' => '包裹重量',
            'width' =>75,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'delivery_cost_expect' => array (
            'type' => 'money',
            'default' => '0',
            'editable' => false,
            'width' =>75,
            'label' => '预计物流费用',
            'comment' => '预计物流费用(包裹重量计算的费用)',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'delivery_cost_actual' => array (
            'type' => 'money',
            'default' => '0',
            'editable' => false,
            'width' =>75,
            'label' => '实际物流费用',
            'comment' => '实际物流费用(物流公司提供费用)',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'create_time' => array (
            'type' => 'time',
            'label' => '创建时间',
            'editable' => false,
            'filtertype' => 'time',
            'width' => 130,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 98,
        ),
        'delivery_time' => array (
            'type' => 'time',
            'label' => '发货时间',
            'default' => 0,
            'editable' => false,
            'filtertype' => 'time',
            'width' => 130,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 30,
        ),
        'order_id' => array(
            'type' => 'int unsigned',
            'label' => '订单ID',
            'default' => 0,
            'editable' => false,
            'width' => 180,
            'in_list' => false,
            'default_in_list' => false,
        ),
        'order_bn' => array(
            'type' => 'varchar(50)',
            'label' => '订单号',
            'width' => 190,
            'searchtype' => 'nequal',
            'filtertype' => 'textarea',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 15,
        ),
        'package_bn' => array (
            'type' => 'varchar(50)',
            'editable' => false,
            'label' => '京东订单号',
            'width' =>140,
            'searchtype' => 'nequal',
            'filtertype' => 'textarea',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 10,
        ),
        'last_modified' => array(
            'label' => '最后更新时间',
            'type' => 'last_modify',
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'order' => 99,
        ),
        'sync_status' => array (
            'type' => array(
                'none' => '未请求',
                'fail' => '失败',
                'succ' => '成功',
            ),
            'default' => 'none',
            'width' => 130,
            'label' => '同步状态',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 80,
        ),
        'push_kepler' => array(
            'type' => array(
                'none' => '未回写',
                'fail' => '回写失败',
                'succ' => '回写成功',
                'retry' => '重试推送',
            ),
            'default' => 'none',
            'label' => '推送云交易',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 99,
        ),
        'exception_status' => array(
            'type' => 'int',
            'default' => '0',
            'label' => '异常状态',
            'width' => 90,
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 25,
            'filtertype' => 'normal',
            'filterdefault' => true,
        ),
        'exception_code' => array(
            'type' => 'varchar(255)',
            'label' => '异常代码',
            'width' => 120,
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 26,
        ),
        'sub_exception_code' => array(
            'type' => 'varchar(255)',
            'label' => '子异常代码',
            'width' => 120,
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 27,
        ),
        'exception_type' => array(
            'type' => 'varchar(255)',
            'label' => '异常类型',
            'width' => 120,
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 28,
        ),
        'exception_create_time' => array(
            'type' => 'time',
            'label' => '异常发生时间',
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 29,
            'filtertype' => 'time',
        ),
        'exception_over_time' => array(
            'type' => 'time',
            'label' => '预警转实际异常时间',
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 30,
            'filtertype' => 'time',
        ),
        'exception_id' => array(
            'type' => 'varchar(255)',
            'label' => '异常ID',
            'width' => 120,
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 31,
        ),
        'detail_type' => array(
            'type' => 'int',
            'default' => '0',
            'label' => '详情类型',
            'width' => 90,
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 32,
        ),
        'courier_name' => array(
            'type' => 'varchar(20)',
            'label' => '配送员姓名',
            'editable' => false,
            'width' => 100,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'courier_phone' => array(
            'type' => 'varchar(100)',
            'label' => '配送员联系方式',
            'editable' => false,
            'width' => 120,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'phone_type' => array(
            'type' => array(
                '0' => '真实电话',
                '1' => '隐私号',
            ),
            // 'default' => '0',
            'label' => '电话类型',
            'editable' => false,
            'width' => 90,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'privacy_num_validity_seconds' => array(
            'type' => 'int',
            'label' => '隐私号过期时间',
            'editable' => false,
            'width' => 120,
            'in_list' => true,
            'default_in_list' => false,
        ),
    ),
    'index' => array (
        'index_logi_no' => array (
            'columns' => array (
                0 => 'logi_no',
            ),
        ),
        'index_order_bn' => array(
            'columns' => array(
                0 => 'order_bn',
            ),
        ),
        'index_package_bn' => array(
            'columns' => array(
                0 => 'package_bn',
            ),
        ),
        'index_delivery_bn' => array(
            'columns' => array(
                0 => 'delivery_bn',
            ),
        ),
        'index_status' => array(
            'columns' => array(
                0 => 'status',
            ),
        ),
        'in_delivery_id' => array (
            'columns' => array (
                0 => 'delivery_id',
            ),
        ),
        'index_push_kepler' => array(
            'columns' => array(
                0 => 'push_kepler',
            ),
        ),
        'index_create_time' => array(
            'columns' => array(
                0 => 'create_time',
            ),
        ),
        'index_exception_status' => array(
            'columns' => array(
                0 => 'exception_status',
            ),
        ),
        'index_exception_create_time' => array(
            'columns' => array(
                0 => 'exception_create_time',
            ),
        ),
        'index_exception_code' => array(
            'columns' => array(
                0 => 'exception_code',
            ),
        ),
    ),
    'comment' => '物流包裹单表',
    'engine' => 'innodb',
    'version' => '$Rev: 41996 $',
);
