<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['orders'] = array(
    'columns' => array(
        'order_id'           => array(
            'type'     => 'int unsigned',
            'required' => true,
            'pkey'     => true,
            'editable' => false,
            'extra'    => 'auto_increment',
            'comment' => '自增主键ID'
        ),
        'order_bn'           => array(
            'type'            => 'varchar(32)',
            'required'        => true,
            'label'           => '订单号',
            'is_title'        => true,
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'platform_order_bn' => array (
            'type' => 'varchar(32)',
            'label' => '平台订单号',
            'width' => 180,
            'searchtype' => 'nequal',
            'editable' => false,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'archive'            => array(
            'type'     => 'tinyint unsigned',
            'required' => true,
            'default'  => 0,
            'editable' => false,
            'comment' => '归档状态,可选值:1(是),0(否)'
        ),
        'member_id'          => array(
            'type'     => 'table:members@ome',
            'label'    => '会员用户名',
            'width'    => 150,
            'editable' => false,
            'in_list'  => true,
            'comment'  => '会员ID,关联ome_members.member_id'
        ),
        'confirm'            => array(
            'type'     => 'tinybool',
            'default'  => 'N',
            'required' => true,
            'label'    => '确认状态',
            'width'    => 75,
            'hidden'   => true,
            'editable' => false,
            'comment'  => '订单确认状态,可选值:Y(是),N(否)'
        ),
        'process_status'     => array(
            'type'            => array(
                'unconfirmed'   => '未确认',
                'confirmed'     => '已确认',
                'splitting'     => '部分拆分',
                'splited'       => '已拆分完',
                'cancel'        => '取消',
                'remain_cancel' => '余单撤销',
                'is_retrial'    => '复审订单',
                'is_declare'    => '跨境申报订单',
            ),
            'default'         => 'unconfirmed',
            'required'        => true,
            'label'           => '确认状态',
            'width'           => 70,
            'editable'        => false,
            'filtertype'      => 'yes',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
            'comment' => '订单确认状态,可选值:unconfirmed(未确认),confirmed(已确认),splitting(部分拆分),splited(已拆分完),cancel(取消),remain_cancel(余单撤销),is_retrial(复审订单),is_declare(跨境申报订单)',
        ),
        'splited_num'   => array(
            'label'           => '拆单数', // 表示：拆单次数
            'width'           => 50,
            'type'            => 'number',
            'editable'        => false,
            'filtertype'      => 'yes',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'status'             => array(
            'type'            => array(
                'active' => '活动订单',
                'dead'   => '已作废',
                'finish' => '已完成',
            ),
            'default'         => 'active',
            'required'        => true,
            'label'           => '订单状态',
            'width'           => 75,
            'hidden'          => true,
            'editable'        => false,
            'in_list'         => false,
            'default_in_list' => false,
            'comment' => '订单状态,可选值:active(活动订单),dead(已作废),finish(已完成)',
        ),
        'pay_status'         => array(
            'type'            => array(
                0 => '未支付',
                1 => '已支付',
                2 => '处理中',
                3 => '部分付款',
                4 => '部分退款',
                5 => '全额退款',
                6 => '退款申请中',
                7 => '退款中',
                8 => '支付中',
            ),
            'default'         => '0',
            'required'        => true,
            'label'           => '付款状态',
            'width'           => 75,
            'editable'        => false,
            'filtertype'      => 'yes',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
            'comment' => '付款状态,可选值:0(未支付),1(已支付),2(处理中),3(部分付款),4(部分退款),5(全额退款),6(退款申请中),7(退款中),8(支付中)',
        ),
        'ship_status'        => array(
            'type'            => array(
                0 => '未发货',
                1 => '已发货',
                2 => '部分发货',
                3 => '部分退货',
                4 => '已退货',
            ),
            'default'         => '0',
            'required'        => true,
            'label'           => '发货状态',
            'width'           => 75,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => false,
            'comment' => '发货状态,可选值:0(未发货),1(已发货),2(部分发货),3(部分退货),4(已退货)'
        ),
        'is_delivery'        => array(
            'type'     => 'tinybool',
            'default'  => 'Y',
            'required' => true,
            'editable' => false,
            'label'           => '是否可以发货',
            'in_list'         => true,
            'default_in_list' => false,
            'comment' => '订单是否可发货,可选值:Y(是),N(否)'
        ),
        'shipping'           => array(
            'type'     => 'varchar(100)',
            'label'    => '配送方式',
            'width'    => 75,
            'editable' => false,
            'sdfpath'  => 'shipping/shipping_name',
            'in_list'  => false,
            'default_in_list' => false,
        ),
        'pay_bn'             => array(
            'type'     => 'varchar(255)',
            'editable' => false,
            'label'    => '支付编号',
        ),
        'payment'            => array(
            'type'            => 'varchar(100)',
            'label'           => '支付方式',
            'width'           => 65,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => false,
            'sdfpath'         => 'payinfo/pay_name',
        ),
        'weight'             => array(
            'type'     => 'money',
            'editable' => false,
            'comment' => '订单重量,单位:g',
        ),
        'tostr'              => array(
            'type'     => 'longtext',
            'editable' => false,
            'sdfpath'  => 'title',
            'comment' => '订单明细简写,JSON格式保存',
        ),
        'itemnum'            => array(
            'type'     => 'number',
            'editable' => false,
            'comment' => '订单明细数量',
        ),
        'createtime'         => array(
            'type'          => 'time',
            'label'         => '下单时间',
            'width'         => 130,
            'editable'      => false,
            'filtertype'    => 'time',
            'filterdefault' => true,
            'in_list'       => true,
        ),
        'download_time'      => array(
            'type'     => 'time',
            'label'    => '订单下载时间',
            'width'    => 130,
            'editable' => false,
            'in_list'  => true,
        ),
        'up_time'            => array(
            'type'     => 'time',
            'label'    => '订单回传时间',
            'width'    => 130,
            'editable' => false,
        ),
        'last_modified'      => array(
            'label'    => '最后更新时间',
            'type'     => 'last_modify',
            'width'    => 130,
            'editable' => false,
            'in_list'  => true,
        ),
        'outer_lastmodify'   => array(
            'label'    => '前端店铺最后更新时间',
            'type'     => 'time',
            'width'    => 130,
            'editable' => false,
            'in_list'  => true,
        ),
        'shop_id'            => array(
            'type'          => 'varchar(32)',
            'label'         => '来源店铺',
            'width'         => 75,
            'editable'      => false,
            'in_list'       => true,
            'filtertype'    => 'normal',
            'filterdefault' => true,
        ),
        'shop_type'          => array(
            'type'          => 'varchar(50)',
            'label'         => '店铺类型',
            'width'         => 75,
            'editable'      => false,
            'in_list'       => true,
            'filtertype'    => 'normal',
            'filterdefault' => true,
        ),
        //收货人信息
        'ship_name'          => array(
            'type'            => 'varchar(255)',
            'label'           => '收货人',
            'sdfpath'         => 'consignee/name',
            'editable'        => false,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'ship_area'          => array(
            'type'          => 'region',
            'label'         => '收货地区',
            'width'         => 170,
            'editable'      => false,
            'filtertype'    => 'yes',
            'filterdefault' => true,
            'sdfpath'       => 'consignee/area',
            'in_list'       => true,
        ),
        'ship_addr'          => array(
            'type'       => 'text',
            'label'      => '收货地址',
            'width'      => 180,
            'editable'   => false,
            'filtertype' => 'normal',
            'sdfpath'    => 'consignee/addr',
            'in_list'    => true,
        ),
        'ship_zip'           => array(
            'label'    => '收货邮编',
            'type'     => 'varchar(20)',
            'editable' => false,
            'sdfpath'  => 'consignee/zip',
            'in_list'  => true,
        ),
        'ship_tel'           => array(
            'type'     => 'varchar(200)',
            'label'    => '收货人电话',
            'width'    => 120,
            'editable' => false,
            'sdfpath'  => 'consignee/telephone',
            'in_list'  => true,
        ),
        'ship_email'         => array(
            'type'     => 'varchar(150)',
            'editable' => false,
            'sdfpath'  => 'consignee/email',
            'label' => '收货人邮箱',
        ),
        'ship_time'          => array(
            'type'     => 'varchar(50)',
            'editable' => false,
            'sdfpath'  => 'consignee/r_time',
            'label' => '要求到货时间',
            'comment' => '要求到货时间',
            'in_list' => true,
        ),
        'ship_mobile'        => array(
            'label'    => '收货人手机',
            'hidden'   => true,
            'type'     => 'varchar(200)',
            'editable' => false,
            'width'    => 120,
            'sdfpath'  => 'consignee/mobile',
            'in_list'  => true,
        ),
        //发货人信息
        'consigner_name'     => array(
            'type'            => 'varchar(50)',
            'label'           => '发货人',
            'sdfpath'         => 'consigner/name',
            'width'           => 60,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'consigner_area'     => array(
            'type'     => 'region',
            'label'    => '发货人地区',
            'width'    => 170,
            'editable' => false,
            'sdfpath'  => 'consigner/area',
            'in_list'  => true,
        ),
        'consigner_addr'     => array(
            'type'     => 'varchar(100)',
            'label'    => '发货人地址',
            'width'    => 180,
            'editable' => false,
            'sdfpath'  => 'consigner/addr',
            'in_list'  => true,
        ),
        'consigner_zip'      => array(
            'label'    => '发货人邮编',
            'type'     => 'varchar(20)',
            'editable' => false,
            'sdfpath'  => 'consigner/zip',
            'in_list'  => true,
        ),
        'consigner_email'    => array(
            'type'     => 'varchar(150)',
            'label'    => '发货人e-mail',
            'editable' => false,
            'sdfpath'  => 'consigner/email',
        ),
        'consigner_mobile'   => array(
            'label'    => '发货人手机',
            'hidden'   => true,
            'type'     => 'varchar(50)',
            'editable' => false,
            'width'    => 85,
            'sdfpath'  => 'consigner/mobile',
            'in_list'  => true,
        ),
        'consigner_tel'      => array(
            'type'     => 'varchar(30)',
            'label'    => '发货人电话',
            'width'    => 75,
            'editable' => false,
            'sdfpath'  => 'consigner/tel',
            'in_list'  => true,
        ),
        'delivery_time'         => array(
            'type'          => 'time',
            'label'         => '发货时间',
            'width'         => 130,
            'editable'      => false,
            'filtertype'    => 'time',
            'filterdefault' => true,
            'in_list'       => true,
        ),
        //商品信息
        'cost_item'          => array(
            'type'     => 'money',
            'default'  => '0',
            'required' => true,
            'editable' => false,
            'in_list'  => true,
            'label'    => '商品金额',
            'width'    => 75,
        ),
        'is_tax'             => array(
            'type'          => 'bool',
            'default'       => 'false',
            'required'      => true,
            'editable'      => false,
            'in_list'       => true,
            'label'         => '是否开发票',
            'width'         => 80,
            'filtertype'    => 'yes',
            'filterdefault' => true,
        ),
        'cost_tax'           => array(
            'type'     => 'money',
            'default'  => '0',
            'required' => true,
            'editable' => false,
            'in_list'  => true,
            'width'    => 65,
            'label'    => '税金',
        ),
        'tax_company'        => array(
            'type'     => 'varchar(255)',
            'editable' => false,
            'sdfpath'  => 'tax_title',
            'label'    => '发票抬头'
        ),
        'cost_freight'       => array(
            'type'       => 'money',
            'default'    => '0',
            'required'   => true,
            'label'      => '配送费用',
            'width'      => 70,
            'editable'   => false,
            'filtertype' => 'number',
            'sdfpath'    => 'shipping/cost_shipping',
            'in_list'    => true,
        ),
        'is_protect'         => array(
            'type'     => 'bool',
            'default'  => 'false',
            'required' => true,
            'editable' => false,
            'sdfpath'  => 'shipping/is_protect',
            'comment'  => '保价状态,可选值:true(是),false(否)'
        ),
        'cost_protect'       => array(
            'type'            => 'money',
            'default'         => '0',
            'label'           => '保价费用',
            'required'        => true,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => false,
            'sdfpath'         => 'shipping/cost_protect',
        ),
        'is_cod'             => array(
            'type'            => 'bool',
            'required'        => true,
            'default'         => 'false',
            'editable'        => false,
            'label'           => '货到付款',
            'sdfpath'         => 'shipping/is_cod',
            'in_list'         => true,
            'default_in_list' => false,
            'width'           => 60,
        ),
        'refund_money'       => array(
            'type'            => 'money',
            'default'         => '0',
            'label'           => '价保费用',
            'required'        => true,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => false,
            
        ),
        'is_fail'            => array(
            'type'     => 'bool',
            'required' => true,
            'default'  => 'false',
            'editable' => false,
            'label'    => '失败订单',
        ),
        'edit_status'        => array(
            'type'     => 'bool',
            'required' => true,
            'default'  => 'false',
            'editable' => false,
            'comment' => '订单编辑状态,可选值:true(是),false(否)'
        ),
        'cost_payment'       => array(
            'type'     => 'money',
            'editable' => false,
            'sdfpath'  => 'payinfo/cost_payment',
            'comment' => '订单支付手续费',
        ),
        'currency'           => array(
            'in_list'         => true,
            'default_in_list' => false,
            'type'            => 'varchar(8)',
            'editable'        => false,
            'label'           => '货币',
        ),
        'cur_rate'           => array(
            'type'     => 'decimal(10,4)',
            'default'  => '1.0000',
            'editable' => false,
            'label'           => '货币汇率',
        ),
        'score_u'            => array(
            'type'     => 'money',
            'default'  => '0',
            'required' => true,
            'editable' => false,
            'label'           => '用户使用积分'
        ),
        'score_g'            => array(
            'type'     => 'money',
            'default'  => '0',
            'required' => true,
            'editable' => false,
            'label'    => '用户获得积分',
        ),
        'discount'           => array(
            'type'            => 'money',
            'default'         => '0',
            'required'        => true,
            'editable'        => false,
            'label'           => '折扣',
            'in_list'         => true,
            'default_in_list' => false,
            'width'           => 60,
            'comment'         => '订单折扣',
        ),
        'pmt_goods'          => array(
            'type'            => 'money',
            'default'         => '0',
            'required'        => true,
            'editable'        => false,
            'label'           => '商品优惠',
            'in_list'         => true,
            'default_in_list' => false,
            'comment'         => '订单商品优惠',
        ),
        'pmt_order'          => array(
            'type'            => 'money',
            'default'         => '0',
            'required'        => true,
            'editable'        => false,
            'label'           => '订单优惠',
            'in_list'         => true,
            'default_in_list' => false,
            'comment'         => '订单整单优惠'
        ),
        'total_amount'       => array(
            'type'            => 'money',
            'default'         => '0',
            'label'           => '订单总额',
            'width'           => 70,
            'editable'        => false,
            'filtertype'      => 'number',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'final_amount'       => array(
            'type'     => 'money',
            'default'  => '0',
            'required' => true,
            'editable' => false,
            'sdfpath'  => 'cur_amount',
            'comment' => '订单换算汇率后总额'
        ),
        'payed'              => array(
            'type'            => 'money',
            'default'         => '0',
            'editable'        => false,
            'label'           => '已付金额',
            'width'           => 75,
            'in_list'         => true,
            'default_in_list' => false,
            'comment' => '订单已支付金额',
        ),
        'api_version'       => array(
            'type'     => 'varchar(10)',
            'default'  => '1.0',
            'comment'  => '接口版本号',
            'editable' => false,
        ),
        'custom_mark'        => array(
            'type'     => 'longtext',
            'label'    => '客户备注',
            'editable' => false,
        ),
        'mark_text'          => array(
            'type'     => 'longtext',
            'label'    => '商家备注',
            'editable' => false,
        ),
        'disabled'           => array(
            'type'     => 'bool',
            'required' => true,
            'default'  => 'false',
            'editable' => false,
            'comment' => '删除状态,可选值:true(是),false(否)'
        ),
        'mark_type'          => array(
            'type'     => 'varchar(3)',
            'label'    => '订单备注图标',
            'hidden'   => true,
            'width'    => 85,
            'editable' => false,
            'in_list'  => true,
        ),
        'tax_no'             => array(
            'type'            => 'varchar(50)',
            'label'           => '发票号',
            'editable'        => false,
            'filtertype'      => 'normal',
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'dt_begin'           => array(
            'type'     => 'time',
            'label'    => '分派开始时间',
            'editable' => false,
            'width'    => 110,
        ),
        'group_id'           => array(
            'type'            => 'table:groups@ome',
            'label'           => '确认组',
            'editable'        => false,
            'width'           => 90,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'op_id'              => array(
            'type'            => 'table:account@pam',
            'label'           => '确认人',
            'editable'        => false,
            'width'           => 60,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'dispatch_time'      => array(
            'type'            => 'time',
            'label'           => '分派时间',
            'editable'        => false,
            'width'           => 130,
            'filtertype'      => 'time',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'order_limit_time'   => array(
            'type'     => 'time',
            'editable' => false,
            'comment' => '订单失效时间'
        ),
        'abnormal'           => array(
            'type'     => 'bool',
            'label'    => '异常处理状态',
            'editable' => false,
            'in_list'  => true,
            'default'  => 'false',
            'filtertype' => 'yes',
            'filterdefault' => true,
            'comment'    => '异常处理状态,可选值:true(是),false(否)',
        ),
        'print_finish'       => array(
            'type'     => 'bool',
            'editable' => false,
            'default'  => 'false',
            'required' => true,
            'comment' => '订单打印完成状态,可选值:true(是),false(否)',
        ),
        'source'             => array(
            'type'     => 'varchar(50)',
            'default'  => 'matrix',
            'editable' => false,
            'comment' => '订单来源,可选值:matrix(矩阵),local(本地),import(导入),after(售后)'
        ),
        'pause'              => array(
            'type'          => 'bool',
            'default'       => 'false',
            'editable'      => false,
            'filtertype'    => 'yes',
            'filterdefault' => true,
            'in_list'       => true,
            'label'         => '暂停',
            'comment' => '订单暂停,可选值:true(是),false(否)',
        ),
        'is_modify'          => array(
            'type'          => 'bool',
            'default'       => 'false',
            'editable'      => false,
            'in_list'       => true,
            'label'         => '商品信息编辑',
            'width'         => 60,
            'filtertype'    => 'yes',
            'filterdefault' => true,
            'comment' => '订单是否修改过商品信息,可选值:true(是),false(否)',
        ),
        'old_amount'         => array(
            'type'     => 'money',
            'default'  => '0',
            'editable' => false,
            'comment' => '订单原金额',
        ),
        'order_type'         => array(
            'type'     => array(
                'normal' => '订单',
                'sale' => '销售单',
                'presale' => '预售订单',
                'vopczc' => '唯品会仓中仓订单',
                'platform' => '平台发货',
                'offline'  => '线下订单',
                'gift'  => '礼品卡订单',
                'integral'  => '积分订单',
                'exchange'  => '换货订单',
                'brush' => '特殊订单',
                'jitxsc' => '唯品会省仓',
                'zerobuy' => '0元购',
                'bufa' => '补发订单',
                'jisuxianhuo' => '急速现货',
                'pinpaizhifa' => '品牌直发',
            ),
            'label'    => '订单类型',
            'default'  => 'normal',
            'editable' => false,
            'in_list'  => true,
            'filtertype'    => 'yes',
            'filterdefault' => true,
            'comment' => '订单类型,可选值: normal(订单), sale(销售单), presale(预售单), vopczc(_only_pcs), platform(平台发货), offline(线下订单), gift(礼品卡订单), integral(积分订单), exchange(换货单), brush(特殊订单), jitxsc(_only_pcs), zerobuy(0元购),jisuxianhuo(急速现货), pinpaizhifa(品牌直发)'
        ),
        'order_combine_idx'  => array(
            'type'     => 'bigint(13)',
            'label'    => '合并索引号',
            'editable' => false,
        ),
        'order_combine_hash' => array(
            'type'     => 'char(32)',
            'label'    => '合并识别号',
            'editable' => false,
        ),
        'auto_status'        => array(
            'type'     => 'bigint(20)',
            'label'    => '状态标识位',
            'editable' => false,
            'default'  => '0',
        ),
        'abnormal_status'    => array(
            'type'     => 'bigint(20)',
            'label'    => '异常状态标识位',
            'editable' => false,
            'default'  => '0',
        ),
        'print_status'       => array(
            'type'     => 'tinyint',
            'required' => true,
            'editable' => false,
            'default'  => '0',
            'width'    => 75,
            'comment'  => '打印状态',
            'label'    => '打印状态',
        ),
        'logi_id'            => array(
            'type'            => 'table:dly_corp@ome',
            'comment'         => '物流公司ID,关键ome_dly_corp.corp_id',
            'editable'        => false,
            'label'           => '物流公司',
            'in_list'         => true,
            'default_in_list' => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
        ),
        'logi_no'            => array(
            'type'            => 'varchar(50)',
            'label'           => '物流单号',
            'comment'         => '物流单号',
            'editable'        => false,
            'width'           => 130,
            'in_list'         => true,
            'default_in_list' => true,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
        ),
        'sync'               => array(
            'type'          => array(
                'none' => '未回写',
                'run'  => '运行中',
                'fail' => '回写失败',
                'succ' => '回写成功',

            ),
            'default'       => 'none',
            'label'         => '回写状态',
            'editable'      => false,
            'filtertype'    => 'yes',
            'filterdefault' => true,
            'comment' => '回写状态,可选值: none(未回写), run(运行中), fail(回写失败), succ(回写成功)',
        ),
        'paytime'            => array(
            'type'     => 'time',
            'label'    => '付款时间',
            'width'    => 130,
            'editable' => false,
            'in_list'  => true,
        ),
        'modifytime'         => array(
            'type'     => 'time',
            'label'    => '最后修改时间',
            'width'    => 130,
            'editable' => false,
            'in_list'  => true,
        ),
        'is_auto'            => array(
            'type'       => 'bool',
            'default'    => 'false',
            'required'   => true,
            'label'      => '是否自动处理',
            'editable'   => false,
            'filtertype' => 'normal',
            'in_list'    => true,
            'comment' => '是否自动处理,可选值:true(是),false(否)',
        ),
        'self_delivery'      => array(
            'type'       => 'bool',
            'default'    => 'true',
            'required'   => true,
            'label'      => '是否自发货',
            'editable'   => false,
            'filtertype' => 'normal',
            'in_list'    => true,
            'comment' => '是否自发货,可选值:true(是),false(否)',
        ),
        'order_source'       => array(
            'type'            => 'varchar(50)',
            'label'           => '来源渠道',
            'default'         => 'direct',
            'filtertype'      => 'yes',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'relate_order_bn'    => array(
            'type'            => 'varchar(32)',
            'label'           => '关联订单号',
            'width'           => 130,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'createway'          => array(
            'type'       => array(
                'matrix' => '平台获取',
                'local'  => '手工新建',
                'import' => '批量导入',
                'after'  => '售后自建',
                'yjdf'  => '云交易售后自建',
            ),
            'label'      => '订单生成类型',
            'default'    => 'matrix',
            'required'   => true,
            'in_list'    => true,
            'filtertype' => 'normal',
            'comment' => '订单生成类型,可选值:matrix(平台获取),local(手工新建),import(批量导入),after(售后自建),yjdf(云交易售后自建)',
        ),
        'sync_fail_type'     => array(
            'type'     => array(
                'none'    => '未知错误',
                'shipped' => '前端已发货',
                'unbind'  => '店铺未绑定',
                'params'  => '参数错误',
                'logistics' => '物流错误',
            ),
            'default'  => 'none',
            'label'    => '回写失败类型',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'comment' => '回写失败类型,可选值:none(未知错误),shipped(前端已发货),unbind(店铺未绑定),params(参数错误),logistics(物流错误)',
        ),
        'omnichannel'        => array(
            'type'     => 'tinyint(1)',
            'label'    => '全渠道订单',
            'editable' => false,
            'default'  => '2',
            'comment' => '全渠道订单,可选值:1(是),2(否)',
        ),
        'is_service_order'   => array(
            'type'            => 'bool',
            'default'         => 'false',
            'label'           => '是否服务订单',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'comment' => '是否服务订单,可选值:true(是),false(否)',
        ),
        'service_price'      => array(
            'type'     => 'money',
            'default'  => '0',
            'editable' => false,
            'label'    => '服务费用',
        ),
        'platform_service_fee' => array(
            'type'     => 'money',
            'default'  => '0',
            'editable' => false,
            'label'    => '平台服务费用',
        ),
        'order_bool_type'    => array(
            'type'     => 'bigint(20)',
            'label'    => '订单种类',
            'editable' => false,
            'default'  => '0',
        ),
        'end_time'           => array(
            'type'            => 'time',
            'label'           => '买家确认收货时间',
            'width'           => 130,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'org_id'             => array(
            'type'            => 'number',
            'label'           => '运营组织',
            'editable'        => false,
            'width'           => 60,
            'filtertype'      => 'normal',
            'filterdefault'   => false,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'source_status'      => array(
            'type'            => 'varchar(64)',
            'label'           => '平台状态',
            'editable'        => false,
            'width'           => 120,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'timing_confirm'     => array(
            'type'    => 'time',
            'label'   => '定时审单',
            'default' => '0',
            'filtertype'      => 'date',
            'filterdefault'   => true,
            'in_list'         => false,
            'default_in_list' => false,
        ),
        'presale_status'       => array(
            'type'    => array(
                0 => '非预售',
                1 => '全部预售',
                2 => '部分预售',
            ),
            'default' => '0',
            'label'   => '预售状态',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
            'comment' => '预售状态,可选值:0(非预售),1(全部预售),2(部分预售)',
        ),
        'is_assign_store'=> array(
            'type' => 'bool',
            'default' => 'false',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'label' => '是否指定仓发货',
            'width' => 70,
        ),
        'step_trade_status'=>array(
            'type'            => 'varchar(90)',
            'label'           => '分阶段付款的订单状态',
            'editable'        => false,
            'width'           => 120,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'bufa_reason' => array(
            'type'            => 'varchar(255)',
            'label'           => '补发原因',
            'editable'        => false,
            'width'           => 120,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        // 'ip' =>
        //     array (
        //         'type' => 'varchar(15)',
        //         'editable' => false,//(协同版)
        //     ),
        // 'is_anti' =>
        //     array (
        //         'type' => 'bool',
        //         'required' => true,
        //         'default' => 'false',
        //         'editable' => false,//(协同版)
        //     ),
        'coupons_name' =>
            array (
                'type' => 'varchar(255)',
                'editable' => false,//(协同版)
            ),
        // 'refer_id' =>
        //     array (
        //         'type' => 'varchar(50)',
        //         'label' => '首次来源ID',//(协同版)
        //         'width' => 75,
        //         'editable' => false,
        //     ),
        // 'refer_url' =>
        //     array (
        //         'type' => 'varchar(200)',
        //         'label' => '首次来源URL',//(协同版)
        //         'width' => 150,
        //         'editable' => false,
        //     ),
        // 'refer_time' =>
        //     array (
        //         'type' => 'time',
        //         'label' => '首次来源时间',//(协同版)
        //         'width' => 110,
        //         'editable' => false,
        //     ),
        // 'c_refer_id' =>
        //     array (
        //         'type' => 'varchar(50)',
        //         'label' => '本次来源ID',//(协同版)
        //         'width' => 75,
        //         'editable' => false,
        //     ),
        // 'c_refer_url' =>
        //     array (
        //         'type' => 'varchar(200)',
        //         'label' => '本次来源URL',//(协同版)
        //         'width' => 150,
        //         'editable' => false,
        //     ),
        // 'c_refer_time' =>
        //     array (
        //         'type' => 'time',
        //         'label' => '本次来源时间',//(协同版)
        //         'width' => 110,
        //         'editable' => false,
        //     ),
        // 'order_job_no' =>
        //     array (
        //         'type' => 'varchar(16)',
        //         'label' => '批次索引号',//(协同版)
        //         'editable' => false,
        //     ),
        'refund_status' =>
            array (
                'type' => 'integer',
                'default' => 0,
                'label' => '退款状态',//(协同版)
                'editable' => false,
            ),
        // 'extra_info'=>array(
        //     'type'=>'varchar(25)',
        //     'label'=>'交易分类编码',//(协同版)
        //     'filtertype' => 'yes',
        //     'filterdefault' => true,
        //     'in_list'=>true,
        //     'default_in_list'=>true,
        // ),
        'betc_id' => array(
            'type' => 'int unsigned',
            'default' => 0,
            'editable' => false,
            'label' => '贸易公司ID',
        ),
        'cos_id' => array(
            'type' => 'int unsigned',
            'default' => 0,
            'editable' => false,
            'label' => '组织架构ID',
        ),
    ),
    'index'   => array(
        'ind_order_bn_shop'    => array('columns' => array(0 => 'order_bn', 1 => 'shop_id'), 'prefix' => 'unique'),
      
        'ind_archive'          => array('columns' => array(0 => 'archive')),
        // 'ind_ship_status'      => array('columns' => array(0 => 'ship_status')),
        'ind_pay_status'       => array('columns' => array('pay_status','paytime')),
        'ind_status'           => array('columns' => array(0 => 'status')),
        // 'ind_process_status'   => array('columns' => array(0 => 'process_status')),
        'ind_shop_type'        => array('columns' => array(0 => 'shop_type')),
        'ind_is_cod'           => array('columns' => array(0 => 'is_cod')),
        'ind_createtime'       => array('columns' => array(0 => 'createtime')),
        'ind_pay_bn'           => array('columns' => array(0 => 'pay_bn')),
        'ind_is_auto'          => array('columns' => array(0 => 'is_auto')),
        'ind_is_tax'           => array('columns' => array(0 => 'is_tax')),
        'ind_outer_lastmodify' => array('columns' => array(0 => 'outer_lastmodify')),
        'ind_pause'            => array('columns' => array(0 => 'pause')),
        'ind_abnormal'         => array('columns' => array(0 => 'abnormal')),
        'ind_ship_mobile'      => array('columns' => array(0 => 'ship_mobile')),
        'ind_ship_tel'         => array('columns' => array(0 => 'ship_tel')),
        'ind_ship_name'        => array('columns' => array(0 => 'ship_name')),
        'ind_ship_addr'        => array('columns' => array(0 => 'ship_addr(255)')),
        // 'ind_is_fail'          => array('columns' => array(0 => 'is_fail')),
        'ind_logi_no'          => array('columns' => array(0 => 'logi_no')),
        'ind_splited_num'      => array('columns' => array(0 => 'splited_num')),
        'ind_end_time'         => array('columns' => array(0 => 'end_time')),
        'ind_delivery_time'       => array('columns' => array(0 => 'delivery_time')),
        'ind_sync' => array('columns' =>array(0 => 'sync',) ),
        'ind_order_source' => array('columns' =>array(0 => 'order_source',),),
        'ind_relate_order_bn' => array(
            'columns' => array(
                0 => 'relate_order_bn',
            ),
        ),
        'ind_platform_order_bn' => array(
            'columns' => array(
                0 => 'platform_order_bn',
            ),
        ),
        'ind_last_modified' => array(
            'columns' => array(
                0 => 'last_modified',
            ),
        ),
        'ind_order_type' => array(
            'columns' => array(
                0 => 'order_type',
            ),
        ),
        'ind_orgid_shipstatus_isfail_ordertype_status' => array(
            'columns' => array(
                0 => 'org_id',
                1 => 'ship_status',
                2 => 'is_fail',
                3 => 'order_type',
                4 => 'status',
            ),
        ),
        'idx_ship_isfail_ordertype_status' => array(
            'columns' => array(
                0 => 'ship_status',
                1 => 'is_fail',
                2 => 'order_type',
                3 => 'status',
            ),
        ),
        'ind_org_status_isfail_edit_archive' => array(
            'columns' => array(
                0 => 'org_id',
                1 => 'status',
                2 => 'is_fail',
                3 => 'edit_status',
                4 => 'archive',
            ),
        ),
        'idx_isfail_ordertype_paytime' => array(
            'columns' => array(
                0 => 'is_fail',
                1 => 'order_type',
                2 => 'paytime',
            ),
        ),
        'idx_shopid_isfail_ordertype' => array(
            'columns' => array(
                0 => 'shop_id',
                1 => 'is_fail',
                2 => 'order_type',
            ),
        ),
        'idx_shipstatus_status_logino' => array(
            'columns' => array(
                0 => 'ship_status',
                1 => 'status',
                2 => 'logi_no',
            ),
        ),
        'idx_shipstatus_createway_logino_status' => array(
            'columns' => array(
                0 => 'ship_status',
                1 => 'createway',
                2 => 'logi_no',
                3 => 'status',
            ),
        ),
        'idx_shipstatus_status_createway_sync_logino' => array(
            'columns' => array(
                0 => 'ship_status',
                1 => 'status',
                2 => 'createway',
                3 => 'sync',
                4 => 'logi_no',
            ),
        ),
        'idx_processstatus_status_createtime' => array(
            'columns' => array(
                0 => 'process_status',
                1 => 'status',
                2 => 'createtime',
            ),
        ),
        'idx_total_payed_process_pay_ship_isfail_org' => [
            'columns'   =>  [
                'org_id',
                'process_status',
                'total_amount',
                'payed',
                'pay_status',
                'ship_status',
                'is_fail',
                'last_modified',
            ],
        ],
        'idx_disabled_isfail_shipstatus' => [
            'columns'   =>  [
                'disabled',
                'is_fail',
                'ship_status',
            ],
        ],
        'idx_orgid_ordertype_isfail_archive_disabled_processstatus' => [
            'columns'   =>  [
                'org_id',
                'order_type',
                'is_fail',
                'archive',
                'disabled',
                'process_status',
            ],
        ],
        'ind_betc_id' => array(
            'columns' => array(
                0 => 'betc_id',
            ),
        ),
        'ind_cos_id' => array(
            'columns' => array(
                0 => 'cos_id',
            ),
        ),
    ),
    'comment' => '订单表,用于存储全渠道订单',
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
    'charset' => 'utf8mb4',
);
