<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['return_product_problem'] = array(
    'columns' => array(
        'problem_id'      => array(
            'type'     => 'number',
            'required' => true,
            'pkey'     => true,
            'label'    => '类型自增ID',
            'editable' => false,
            'extra'    => 'auto_increment',
            'order'    => 1,
        ),
        'problem_name'    => array(
            'type'            => 'varchar(100)',
            'required'        => true,
            'is_title'        => true,
            'default'         => '',
            'label'           => '售后原因',
            'width'           => 240,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 10,
        ),
        'problem_type'    => array(
            'type'            => array(
                'shop' => 'shop店铺',
                'wms'  => 'WMS仓储',
            ),
            'default'         => 'shop',
            'width'           => 130,
            // 'required'        => true,
            'editable'        => false,
            'label'           => '单据类型',
            // 'filtertype'      => 'normal',
            // 'filterdefault'   => true,
            // 'in_list'         => true,
            // 'default_in_list' => true,
            'order'           => 20,
        ),
        'platform_type'   => array(
            'type'            => 'varchar(32)',
            // 'required'        => false,
            'default'         => '',
            'label'           => '平台类型',
            // 'filtertype'      => 'normal',
            // 'filterdefault'   => true,
            // 'in_list'         => true,
            // 'default_in_list' => false,
            'width'           => 120,
            'order'           => 30,
        ),
        'reason_id'       => array(
            'type'            => 'varchar(30)',
            // 'required'        => false,
            'default'         => 0,
            'label'           => '前端售后原因ID',
            'width'           => 120,
            // 'in_list'         => true,
            // 'default_in_list' => true,
            'editable'        => false,
            'order'           => 9,
        ),
        'disabled'        => array(
            'type'            => 'bool',
            'default'         => 'false',
            // 'required'        => true,
            'label'           => '是否屏蔽',
            'comment'         => '是否屏蔽（true：是；false：否）',
            'width'           => 110,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 40,
        ),
        'defaulted'       => array(
            'type'            => 'bool',
            'editable'        => false,
            'default'         => 'false',
            'label'           => '是否默认',
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 41,
        ),
        'last_sync_time'  => array(
            'type'            => 'time',
            'editable'        => false,
            'label'           => '最后同步时间',
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 98,
        ),
        'createtime'      => array(
            'type'            => 'time',
            'label'           => '创建时间',
            'width'           => 130,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 99,
        ),
        'rel_reason_id'   => array(
            'type'            => 'varchar(30)',
            'label'           => '关联售后原因ID',
            'width'           => 130,
            // 'in_list'         => true,
            // 'default_in_list' => true,
            'editable'        => false,
            'order'           => 50,
        ),
        'rel_reason_name' => array(
            'type'            => 'varchar(100)',
            'label'           => '关联售后原因',
            'width'           => 150,
            'editable'        => false,
            // 'in_list'         => true,
            // 'default_in_list' => true,
            'order'           => 60,
        ),
    ),
    'index'   => array(
        'ind_disabled'     => array('columns' => array(0 => 'disabled')),
        'ind_problem_name' => array('columns' => array(0 => 'problem_name')),
    ),
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
    'comment' => '售后问题类型表',
);
