<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['return_product'] = array(
    'columns' => array(
        'return_id'          => array(
            'type'     => 'int unsigned',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'editable' => false,
            'label'    => '售后ID',
            'comment'  => '售后ID',
        ),
        'return_bn'          => array(
            'type'            => 'varchar(32)',
            'required'        => true,
            'label'           => '退货记录流水号',
            'comment'         => '退货记录流水号',
            'editable'        => false,
            'searchtype'      => 'nequal',
            'filtertype'      => 'yes',
            'in_list'         => true,
            'default_in_list' => true,
            'is_title'        => true,
        ),
        'order_id'           => array(
            'type'            => 'table:orders@ome',
            'label'           => '订单号',
            'comment'         => '订单号',
            'editable'        => false,
            'in_list'         => false,
            'default_in_list' => false,
        ),
        'platform_order_bn' =>array (
            'type' => 'varchar(32)',
            'label' => '平台订单号',
            'width' => 180,
            'searchtype' => 'nequal',
            'editable' => false,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'title'              => array(
            'type'     => 'varchar(255)',
            'editable' => false,
            'in_list'  => true,
            'label'    => '退货记录标题',
        ),
        'content'            => array(
            'type'            => 'longtext',
            'editable'        => false,
            'label'           => '申请售后原因',
            'comment'         => '申请售后原因',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'attachment'         => array(
            'type'     => 'text',
            'editable' => false,
            'label'    => '附件',
            'comment'  => '附件',
        ),
        'product_data'       => array(
            'type'     => 'longtext',
            'editable' => false,
        ),
        'comment'            => array(
            'type'     => 'longtext',
            'editable' => false,
            'label'    => '申请售后留言',
            'comment'  => '申请售后留言',
        ),
        'add_time'           => array(
            'type'            => 'time',
            'editable'        => false,
            'label'           => '申请时间',
            'filtertype'      => 'time',
            'filterdefault' => true,
            'default_in_list' => true,
            'in_list'         => true,
            'width'           => 130,
        ),
        'disabled'           => array(
            'type'     => 'bool',
            'required' => true,
            'default'  => 'false',
            'editable' => false,
            'label'    => '是否启用',
            'comment'  => '是否启用',
        ),
        'shop_id'            => array(
            'type'     => 'table:shop@ome',
            'editable' => false,
            'label'    => '店铺',
            'in_list'  => true,
        ),
        'delivery_mode'     => array(
            'type'     => 'varchar(32)',
            'label'    => '来源店铺发货模式',
            'default'  => '',
            'comment'  => '可选值请参考ome_shop表的delivery_mode (self=>自发,jingxiao=>经销)'
        ),
        'member_id'          => array(
            'type'     => 'table:members@ome',
            'editable' => false,
        ),
        'process_data'       => array(
            'type'     => 'longtext',
            'editable' => false,
            'comment'  => '存储售后商品信息和仓库收货信息等',
        ),
        'memo'               => array(
            'type'     => 'longtext',
            'editable' => false,
            'label'    => '备注',
            'comment'  => '备注',
        ),
        'money'              => array(
            'type'            => 'money',
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => true,
            'label'           => '最后合计金额',
            'width'           => 90,
        ),
        'op_id'              => array(
            'type'     => 'table:account@pam',
            'editable' => false,
            'label'    => '操作员ID',
            'comment'  => '操作员ID',
        ),
        'refundmoney'        => array(
            'type'            => 'money',
            'editable'        => false,
            'label'           => '退款金额',
            'in_list'         => true,
            'default_in_list' => true,
            'width'           => 75,
        ),
        'delivery_id'        => array(
            'type'            => 'table:delivery@ome',
            'editable'        => false,
            'label'           => '发货单号',
            'in_list'         => false,
            'default_in_list' => false,
            'width'           => 150,
        ),
        'post_fee_bear_role' => array(
            'type'     => 'varchar(20)',
            'editable' => false,
            'label'    => '邮费承担方',
            'default'  => '',
            'in_list'  => false,
        ),
        'status'             => array(
            'type'            => array(
                1 => '申请中',
                2 => '审核中',
                3 => '接受申请',
                4 => '完成',
                5 => '拒绝',
                6 => '买家已经退货，等待卖家确认收货',
                7 => '已质检',
                8 => '补差价',
                9 => '已拒绝退款',
                10 => '卖家拒绝退款',
            ),
            'editable'        => false,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'label'           => '状态',
            'in_list'         => true,
            'default_in_list' => true,
            'required'        => true,
            'default'         => '1',
            'width'           => 175,
        ),
        'last_modified'      => array(
            'label'           => '最后更新时间',
            'type'            => 'last_modify',
            'width'           => 130,
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
        ),
        'tmoney'             => array(
            'type'     => 'money',
            'editable' => false,
            'label'    => '退款的金额',
        ),
        'bmoney'             => array(
            'type'     => 'money',
            'editable' => false,
            'label'    => '补差的金额',
        ),
        'problem_id'         => array(
            'type'            => 'table:return_product_problem@ome',
            'label'           => '售后原因',
            'comment'         => '售后原因',
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'recieved'           => array(
            'type'            => 'bool',
            'required'        => true,
            'default'         => 'false',
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => true,
            'comment'         => '是否收货',
            'label'           => '是否收货',
        ),
        'verify'             => array(
            'type'            => 'bool',
            'required'        => true,
            'default'         => 'false',
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => true,
            'comment'         => '是否质检',
            'label'           => '是否质检',
        ),
        'source'             => array(
            'type'          => 'varchar(50)',
            'default'       => 'local',
            'editable'      => false,
            'label'         => '来源',
            'in_list'       => true,
            'filterdefault' => true,
        ),
        'shop_type'          => array(
            'type'          => 'varchar(50)',
            'label'         => '店铺类型',
            'width'         => 75,
            'editable'      => false,
            'in_list'       => true,
            'filtertype'    => 'normal',
            'filterdefault' => true,
        ),
        'outer_lastmodify'   => array(
            'label'    => '前端店铺最后更新时间',
            'type'     => 'time',
            'width'    => 130,
            'editable' => false,
        ),
        'archive'            => array(
            'type'     => 'tinyint unsigned',
            'required' => true,
            'default'  => 0,
            'editable' => false,
        ),
        'is_fail'            => array(
            'type'     => 'bool',
            'required' => true,
            'default'  => 'false',
            'editable' => false,
            'label'    => '失败售后单',
        ),
        'return_type'        => array(
            'type'            => array(
                'return'   => '退货',
                'change'   => '换货',
                'refund'   => '退款',
                'jdchange' => '京东换货',
            ),
            'default'         => 'return',
            'label'           => '售后类型',
            'in_list'         => true,
            'default_in_list' => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
        ),
        'org_id'             => array(
            'type'            => 'table:operation_organization@ome',
            'label'           => '运营组织',
            'editable'        => false,
            'width'           => 90,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'kinds'              => array(
            'type'            => array(
                'money'  => '售后返现',
                'refund' => '售后退款',
                'reship' => '售后退货',
                'change' => '售后换货',
            ),
            'label'           => '售后类型',
            'comment'         => '售后类型',
            'editable'        => false,
        ),
        'platform_status' => array(
            'type' => 'varchar(30)',
            'editable' => false,
            'label' => '平台售后状态',
            'default' => '',
            'in_list'  => false,
            'default_in_list' => false,
            'filtertype' => 'normal',
            'filterdefault' => true,
        ),
        'is_modify' => array(
            'type' => 'bool',
            'default' => 'false',
            'editable' => false,
            'label' => '平台编辑',
            'width' => 90,
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
        ),
        'apply_remark' => array(
            'type'     => 'longtext',
            'editable' => false,
            'label'    => '售后申请问题描述',
            'comment'  => '售后申请问题描述',
        ),
        'address_id' => array(
            'type' => 'int unsigned',
            'label' => '平台退货地址ID',
            'default'  => 0,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'changebranch_id'    => array(
            'type'     => 'number',
            'editable' => false,
            'label'    => '换货仓库ID',
            'comment'  => '换货仓库ID',
        ),
        'sync_status' => array(
            'type' => array(
                '0' => '无',
                '1' => '同意申请成功',
                '2' => '同意申请失败',
                '3' => '完成退货成功',
                '4' => '完成退货失败',
                '5' => '拒绝申请成功',
                '6' => '拒绝申请失败',
                '7' => '拒绝退货成功',
                '8' => '拒绝退货失败',
            ),
            'default' => '0',
            'width' => 120,
            'required' => true,
            'label' => '同步状态',
            'in_list' => true,
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'sync_msg' => array(
            'type' => 'varchar(200)',
            'label' => '同步失败原因',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'real_refund_amount' => array(
            'type' => 'money',
            'label' => '买家实退',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'flag_type' => array(
            'type' => 'bigint(20)',
            'label' => '标识',
            'editable' => false,
            'default' => '0',
            'in_list'  => false,
            'default_in_list' => false,
        ),
        'jsrefund_flag'           => array(
            'type'            => array(
                0  => '否',
                1  => '是',
            ),
            'default'         => '0',
            'editable'        => false,
            'label'           => '极速退款',
            'width'           => 65,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'refund_shipping_fee' => array(
            'type' => 'money',
            'editable' => false,
            'label' => '退运费金额',
            'in_list' => true,
            'default_in_list' => true,
            'width' => 75,
            'default' => 0,
        ),
        'betc_id' => array(
            'type' => 'int unsigned',
            'default' => 0,
            'editable' => false,
            'label' => '贸易公司ID',
        ),
        'cos_id' => array(
            'type' => 'int unsigned',
            'default' => 0,
            'editable' => false,
            'label' => '组织架构ID',
        ),
        'negotiate_sync_status' => array(
            'type' => array(
                'none' => '不可协商',
                'pending' => '可协商',
                'succ' => '协商发起成功',
                'fail' => '协商发起失败',
                'running' => '协商发起中',
            ),
            'default' => 'pending',
            'editable' => true,
            'label' => '协商状态',
            'comment' => '协商状态',
            'in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
        ),
        'at_time' => array(
            'type' => 'timestamp',
            'default' => 'CURRENT_TIMESTAMP',
            'editable' => false,
            'label' => '创建时间',
            'comment' => '创建时间',
            'in_list' => true,
            'filtertype' => 'time',
            'filterdefault' => true,
        ),
        'up_time' => array(
            'type' => 'timestamp',
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'editable' => false,
            'label' => '更新时间',
            'comment' => '更新时间',
            'in_list' => true,
            'filtertype' => 'time',
            'filterdefault' => true,
        ),
    ),
    'index'   => array(
        'ind_return_bn_shop' => array(
            'columns' => array(
                0 => 'return_bn',
                1 => 'shop_id',
            ),
            'prefix'  => 'unique',
        ),
        'ind_add_time'       => array(
            'columns' => array(
                0 => 'add_time',
            ),
        ),
        'ind_status'         => array(
            'columns' => array(
                0 => 'status',
            ),
        ),
        'ind_last_modified'  => array(
            'columns' => array(
                0 => 'last_modified',
            ),
        ),
        'ind_platform_status' => array(
            'columns' => array(
                0 => 'platform_status',
            ),
        ),
        'idx_deliverymode_isfail' => array(
            'columns' => array(
                0 => 'delivery_mode',
                1 => 'is_fail',
            ),
        ),
        'ind_betc_id' => array(
            'columns' => array(
                0 => 'betc_id',
            ),
        ),
        'ind_cos_id' => array(
            'columns' => array(
                0 => 'cos_id',
            ),
        ),
        'ind_negotiate_sync_status' => array(
            'columns' => array(
                0 => 'negotiate_sync_status',
            ),
        ),
        'ind_at_time' => array(
            'columns' => array(
                0 => 'at_time',
            ),
        ),
        'ind_up_time' => array(
            'columns' => array(
                0 => 'up_time',
            ),
        ),
    ),
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
    'comment' => '售后申请表',
    'charset' => 'utf8mb4',
);
