<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$setting = array(
    'ome.order.failtime'                 => array('type' => SET_T_INT, 'default' => 43200, 'desc' => app::get('base')->_('订单失效时间设置(分钟)')), //一个月
    'ome.order.unconfirmtime'            => array('type' => SET_T_INT, 'default' => 1440, 'desc' => app::get('base')->_('订单未确认的时间设置(分钟)')), //一天
    'ome.delivery.check'                 => array('type' => SET_T_INT, 'default' => 5, 'desc' => app::get('base')->_('发货校验商品数量设置')),
    'ome.branch.mode'                    => array('type' => SET_T_STR, 'default' => 'multi', 'options' => array('single' => app::get('base')->_('单一仓库'), 'multi' => app::get('base')->_('多仓库')), 'desc' => app::get('base')->_('仓库设置')),
    'ome.api_log.clean_time'             => array('type' => SET_T_ENUM, 'default' => '15', 'options' => array('7' => app::get('base')->_('7天'), '15' => app::get('base')->_('半个月'), '21' => app::get('base')->_('21天'), '31' => app::get('base')->_('1个月')), 'desc' => app::get('base')->_('API同步日志备份周期')),
    'purchase.stock.stockset'            => array('type' => SET_T_BOOL, 'default' => 'true', 'desc' => app::get('base')->_('是否条码入库控制'), 'onclick' => 'if(this.value==\'true\'){$$(\'input[name^=set[purchase.stock_confirm]]\').show();$$(\'input[name^=set[purchase.stock_confirm]]\').getParent(\'tr\').show();$$(\'input[name^=set[purchase.stock_cancel]]\').show();$$(\'input[name^=set[purchase.stock_cancel]]\').getParent(\'tr\').show();}if(this.value==\'false\'){$$(\'input[name^=set[purchase.stock_confirm]]\').getParent(\'tr\').hide();$$(\'input[name^=set[purchase.stock_cancel]]\').getParent(\'tr\').hide();}'),
    'purchase.stock_confirm'             => array('type' => SET_T_TXT, 'default' => '99999995', 'desc' => app::get('base')->_('确认按钮内容设置')),
    'purchase.stock_cancel'              => array('type' => SET_T_TXT, 'default' => '11111115', 'desc' => app::get('base')->_('取消按钮内容设置')),
    'purchase.po_type'                   => array('type' => SET_T_ENUM, 'default' => 'credit', 'desc' => app::get('base')->_('采购方式')),
    'ome.delivery.consign'               => array('type' => SET_T_ENUM, 'default' => 'single', 'options' => array('single' => app::get('base')->_('逐个发货'), 'batch' => app::get('base')->_('批量发货')), 'desc' => app::get('base')->_('发货方式')),
    'ome.delivery.check_type'            => array('type' => SET_T_ENUM, 'default' => 'barcode', 'options' => array('barcode' => app::get('ome')->_('条码校验'), 'all' => app::get('ome')->_('整单校验')), 'desc' => app::get('base')->_('发货校验类型')),
    'ome.delivery.check_ident'           => array('type' => SET_T_ENUM, 'default' => 'on', 'options' => array('on' => app::get('ome')->_('开启'), 'off' => app::get('ome')->_('关闭')), 'desc' => app::get('base')->_('打印是否检验批次号')),
    'ome.delivery.weight'                => array('type' => SET_T_ENUM, 'default' => 'on', 'options' => array('on' => app::get('base')->_('开启'), 'off' => app::get('base')->_('关闭')), 'desc' => app::get('base')->_('逐单发货是否称重')),
    'ome.delivery.minWeight'             => array('type' => SET_T_TXT, 'default' => '10', 'desc' => app::get('base')->_('最小包裹重量')),
    'ome.delivery.maxWeight'             => array('type' => SET_T_TXT, 'default' => '30000', 'desc' => app::get('base')->_('最大包裹重量')),
    'ome.delivery.weightwarn'            => array('type' => SET_T_ENUM, 'default' => 'off', 'options' => array('on' => app::get('base')->_('开启'), 'off' => app::get('base')->_('关闭')), 'desc' => app::get('base')->_('逐单发货是否称重报警')),
    'ome.product.serial.merge'           => array('type' => SET_T_BOOL, 'default' => 'false', 'desc' => app::get('base')->_('条码唯一码合并')),
    'ome.product.serial.separate'        => array('type' => SET_T_INT, 'default' => '', 'desc' => app::get('base')->_('条形码与唯一码分隔符')),
    'ome.product.serial.delivery'        => array('type' => SET_T_BOOL, 'default' => 'false', 'desc' => app::get('base')->_('唯一码发货回传')),
    'ome.checkems'                       => array('type' => SET_T_BOOL, 'default' => 'false', 'desc' => app::get('base')->_('是否忽略淘宝拍拍店铺定义的EMS配送方式并在备注中标记')),
    'ome.groupCalibration.intervalTime'  => array('type' => SET_T_INT, 'default' => 2, 'desc' => app::get('base')->_('分组校验时间间隔设置(分钟)')),
    'ome.groupDelivery.intervalTime'     => array('type' => SET_T_INT, 'default' => 2, 'desc' => app::get('base')->_('分组发货时间间隔设置(分钟)')),
    'ome.getOrder.intervalTime'          => array('type' => SET_T_INT, 'default' => 2, 'desc' => app::get('base')->_('订单获取时间间隔设置(分钟)')),
    'ome.delivery.method'                => array('type' => SET_T_ENUM, 'default' => 'off', 'options' => array('on' => app::get('base')->_('启用'), 'off' => app::get('base')->_('不启用')), 'desc' => app::get('base')->_('优先启用【在线下单】方式执行发货操作 (如果不勾选，默认使用【自己联系物流】方式执行发货操作)')),
    'ome.order.mark'                     => array('type' => SET_T_ENUM, 'default' => 'all', 'options' => array('all' => app::get('base')->_('显示全部'), 'last' => app::get('base')->_('显示最新')), 'desc' => app::get('base')->_('订单备注显示方式')),
    'ome.combine.member_id'              => array('type' => SET_T_ENUM, 'default' => '1'),
    'ome.combine.shop_id'                => array('type' => SET_T_ENUM, 'default' => '1'),
    'ome.logi.arrived'                   => array('type' => SET_T_INT, 'default' => '0'),
    'ome.logi.arrived.auto'              => array('type' => SET_T_INT, 'default' => '0'),
    'taoguanallocate.appropriation_type' => array('type' => SET_T_STR, 'default' => 'io', 'options' => array('directly' => app::get('base')->_('直接调拨'), 'io' => app::get('base')->_('出入库调拨')), 'desc' => app::get('base')->_('调拨方式')),
    'ome.orderrpc.mq'                    => array('type' => SET_T_BOOL, 'default' => 'false', 'desc' => app::get('base')->_('订单收订进队列')),
    'ome.wmsrpc.mq'                      => array('type' => SET_T_BOOL, 'default' => 'false', 'desc' => app::get('base')->_('第三方仓储发货进队列')),
    'ome.callback.mq'                    => array('type' => SET_T_BOOL, 'default' => 'false', 'desc' => app::get('base')->_('callback回调进队列')),
    'ome.kernel.log'                     => array('type' => SET_T_BOOL, 'default' => 'false', 'desc' => app::get('base')->_('系统内部日志')),
    'ome.reship.auto_finish'             => array('type' => SET_T_BOOL, 'default' => 'true'),
    'ome.order.presale'                  => array('type' => SET_T_INT, 'default' => '0'),
    'ome.order.presalemoney'             => array('type' => SET_T_INT, 'default' => '0'),
    'ome.order.presale.combine'          => array('type' => SET_T_BOOL, 'default' => '0'),
    'ome.codorder.autopay'               => array('type' => SET_T_BOOL, 'default' => 'true'),
    'ome.saas.apifail_mq'                => array('type' => SET_T_BOOL, 'default' => 'false'),
    'ome.order.split'                    => array('type' => SET_T_INT, 'default' => '0'),
    'ome.hcsafe.config'                  => array('type' => SET_T_BOOL, 'default' => 'true', 'desc' => app::get('base')->_('御城河是否开启')),
    'pam.passport.idaas.enable'          => array('type' => SET_T_BOOL, 'default' => 'true', 'desc' => app::get('base')->_('IDAAS认证是否开启')),
    'ome.iostock.auto_finish'            => array('type' => SET_T_BOOL, 'default' => 'true'),
    'finance.setting.init_time'          => array('type' => SET_T_BOOL, 'default' => 'off', 'desc' => '设置账期'),
    'ome.cn.order.Auto'                  => array('type' => SET_T_BOOL,
        'default'                                            => 'false',
        'desc'                                               => '菜鸟订单自动流转',
        'label'                                              => '自动流转',
        'cate'                                               => 'order'),
    'ome.cn.order.Auto.bindshop'         => array('type' => SET_T_TXT,
        'default'                                            => array(),
        'desc'                                               => '菜鸟订单自动流转',
        'label'                                              => '自动流转',
        'cate'                                               => 'order'),
    'ome.sensitive.data.encrypt'         => array(
        'type'    => SET_T_BOOL,
        'default' => 'true',
        'desc'    => '',
        'label'   => '数据加密',
        'cate'    => 'orderprocess',
    ),

    // 开票设置
    'ome.invoice.mode'                   => array(
        'type'    => SET_T_ENUM,
        'default' => 'paper',
        'desc'    => '',
        'label'   => '默认开票方式',
        'cate'    => 'finance',
    ),
    'ome.invoice.force'                  => array(
        'type'    => SET_T_BOOL,
        'default' => 'off',
        'desc'    => '',
        'label'   => '强制开票',
        'cate'    => 'finance',
    ),
    'ome.invoice.p2e'                    => array(
        'type'    => SET_T_BOOL,
        'default' => 'off',
        'desc'    => '',
        'label'   => '纸质发票开电子',
        'cate'    => 'finance',
    ),
    'ome.order.autoinvoice'              => array(
        'type'    => SET_T_BOOL,
        'default' => 'off',
        'desc'    => '',
        'label'   => '发货后是否开发票',
        'cate'    => 'finance',
    ),
    'ome.invoice.amount.infreight'       => array(
        'type'    => SET_T_BOOL,
        'default' => '0',
        'desc'    => '',
        'label'   => '开票开运费',
        'cate'    => 'finance',
    ),
    'ome.invoice.amount.incoupon'        => array(
        'type'    => SET_T_BOOL,
        'default' => '0',
        'desc'    => '',
        'label'   => '开票开平台券',
        'cate'    => 'finance',
    ),
    'ome.invoice.infreight.category'     => array(
        'type'    => SET_T_TXT,
        'default' => '3040400000000000000',
        'desc'    => '',
        'label'   => '开票运费分类',
        'cate'    => 'finance',
    ),
    'ome.invoice.infreight.name'         => array(
        'type'    => SET_T_TXT,
        'default' => '代收派送服务费',
        'desc'    => '',
        'label'   => '开票运费名称',
        'cate'    => 'finance',
    ),
    'ome.invoice.infreight.rate'         => array(
        'type'    => SET_T_TXT,
        'default' => '0.06',
        'desc'    => '',
        'label'   => '开票运费税率',
        'cate'    => 'finance',
    ),
    'ome.invoice.autoupload'             => array(
        'type'    => SET_T_BOOL,
        'default' => 'off',
        'desc'    => '',
        'label'   => '发票自动上传',
        'cate'    => 'finance',
    ),
    'ome.invoice.gift'             => array(
        'type'    => SET_T_BOOL,
        'default' => 'off',
        'desc'    => '',
        'label'   => '赠品是否开票',
        'cate'    => 'finance',
    ),
    'ome.invoice.local.storage'             => array(
        'type'    => SET_T_BOOL,
        'default' => 'off',
        'desc'    => '',
        'label'   => '发票是否保存',
        'cate'    => 'finance',
    ),
    'ome.invoice.material.type'                   => array(
        'type'    => SET_T_ENUM,
        'default' => 'sales',
        'desc'    => '',
        'label'   => '默认开票物料类型',
        'cate'    => 'finance',
    ),

);
