<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['bill_import'] = array(
    'comment' => '导入记录表',
    'columns' => array(
        'id'          => array(
            'type'     => 'int unsigned',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'editable' => false,
        ),
        'type'        => array(
            'type'            => array(
                'order' => '单号',
                'sku' => 'SKU',
                'sale' => '销售周期',
                'jzt' => '京准通',
                'jdbill' => '京东钱包流水',
            ),
            'label'           => '导入类型',
            'comment'         => 'order:按单号导入,sku:按商品sku明细导入 sale:按销售周期导入',
            'editable'        => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 3,
        ),
        'file_name'        => array(
            'type'            => 'varchar(255)',
            'label'           => '导入文件名',
            'comment'           => '导入文件名',
            'editable'        => false,
            'searchtype'      => 'has',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 2,
        ),
        'error_data'        => array(
            'type'            => 'longtext',
            'label'           => '导入错误数据',
            'comment'           => '导入错误数据',
            'editable'        => false,
            'filtertype'      => 'normal',
            'filterdefault'   => false,
            'in_list'         => false,
            'default_in_list' => false,
            'order' => 4,
        ),
        'money'        => array(
            'type'            => 'money',
            'label'           => '总费用',
            'comment'           => '总费用',
            'editable'        => false,
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 5,
        ),
        'not_confirm_num'        => array(
            'type'            => 'int',
            'label'           => '未确认数量',
            'comment'           => '未确认数量',
            'editable'        => false,
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 6,
        ),
        'not_reconciliation_num'        => array(
            'type'            => 'int',
            'label'           => '未对账数量',
            'comment'           => '未对账数量',
            'editable'        => false,
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 7,
        ),
        'not_matching_num'        => array(
            'type'            => 'int',
            'label'           => '无法匹配数量',
            'comment'           => '无法匹配数量',
            'editable'        => false,
            'filterdefault'   => false,
            'in_list'         => false,
            'default_in_list' => false,
            'order' => 7,
        ),
        'money_unequal_num'        => array(
            'type'            => 'int',
            'label'           => '金额不等数量',
            'comment'           => '金额不等数量',
            'editable'        => false,
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 8,
        ),
        'create_time' => array(
            'type'            => 'time',
            'label'           => '导入时间',
            'comment'         => '导入时间',
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'width' => 130,
            'order' => 9,
        ),
        'start_time' => array(
            'type'            => 'time',
            'label'           => '销售周期开始时间',
            'comment'         => '销售周期开始时间',
            'editable'        => false,
            'filterdefault'   => false,
            'in_list'         => false,
            'default_in_list' => false,
            'order' => 10,
        ),
        'end_time' => array(
            'type'            => 'time',
            'label'           => '销售周期结束时间',
            'comment'         => '销售周期结束时间',
            'editable'        => false,
            'filterdefault'   => false,
            'in_list'         => false,
            'default_in_list' => false,
            'order' => 11,
        ),
        'op_id' =>
            array (
                'type' => 'table:account@pam',
                'label'           => '操作人',
                'comment'         => '操作人',
                'editable' => false,
                'required' => true,
                'filterdefault'   => true,
                'in_list'         => true,
                'default_in_list' => true,
            ),
    ),
    'index' => array(
        'ind_file_name'  => array(
            'columns' => array(
                'file_name',
            ),
        ),
        'ind_type'  => array(
            'columns' => array(
                'type',
            ),
        ),
    ),
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
);
