<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['bill']=array (
  'columns' => 
  array (
    'id' => 
    array (
      'type' => 'bigint unsigned',
      'required' => true,
      'pkey' => true,
      'extra' => 'auto_increment',
      'editable' => false,
    ),
    'unique_id' => array(
      'type' => 'varchar(32)',
      'label' => '单据唯一值',
      'comment' => '单据唯一值',
      'searchtype' => 'nequal',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'trade_no' => array(
      'type' => 'varchar(255)',
      'label' => '业务流水号',
      'comment'=>'业务流水号',
      'is_title' => true,
      'width' => 250,
      'searchtype' => 'nequal',
      'editable' => false,
      'in_list' => true,
      'default_in_list' => true,
      'order'=>5,
    ),
    'out_trade_no' => array(
      'type' => 'varchar(255)',
      'label' => '商户订单号',
      'comment'=>'商户订单号',
      'width' => 180,
      // 'searchtype' => 'nequal',
      // 'editable' => false,
      'in_list' => true,
      'default_in_list' => true,
      'order'=>10,
    ),
    'financial_no' => array(
      'type' => 'varchar(32)',
      'label' => '财务流水号',
      'comment'=>'财务流水号',
      'width' => 180,
      // 'searchtype' => 'nequal',
      // 'editable' => false,
      'in_list' => true,
      'default_in_list' => true,
      'order'=>15,
    ),
    'order_bn' => array(
      'type' => 'varchar(32)',
      'label' => '订单号',
      'comment'=>'订单号',
      'width' => 240,
      // 'searchtype' => 'nequal',
      // 'editable' => false,
      'in_list' => true,
      'default_in_list' => true,
      'order'=>16,
    ),
    'trade_time' => array(
        'type' => 'time',
        'label' => '账单时间',
        'comment'=>'账单时间',
        'width' => 150,
        'editable' => false,
        'in_list' => true,
        'default_in_list' => true,
        'filtertype' => 'normal',
        'filterdefault' => true,
        'order'=>25,
    ),

    'member' => array(
          'type' => 'varchar(50)',
          'label' => '对方名称',
          'comment' => '对方名称',
          'width' => 80,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => false,
          'order'=>50,
    ),

    'money' => array(
          'type' => 'money',
          'required' => true,
          'label'=>'金额',
          'comment' => '金额',
          'width' => 100,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => true,
          'order'=>35,
    ),

    'trade_type' => array(
          'type' => 'varchar(30)',
          'label' => '业务类型',
          'comment' => '业务类型',
          'width' => 130,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => false,
          'order'=>50,
    ),
    'bill_category' => array(
          'type' => 'varchar(50)',
          'label' => '具体类别',
          'comment' => '具体类别',
          'width' => 130,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => false,
          'order'=>60,
    ),
    'remarks' => array(
          'type' => 'varchar(250)',
          'label' => '备注',
          'comment' => '备注',
          'width' => 200,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => false,
          'order'=>50,
    ),
    'create_time' => array(
          'type' => 'time',
          'comment' => '单据生成时间(插入数据库的时间)',
          'required'=>true,
          'editable' => false,
          'in_list' => false,
          'default_in_list' => false,
    ),
    'platform_type' => array(
        'type' => 'varchar(20)',
        'comment'=>'平台类型',
        'default'=>'alipay'

        ),
    'shop_id' => array(
            'type' => 'varchar(32)',
            'editable' => false,
            'label' => '所属店铺',
            'comment'=>'所属店铺',
            'width' => 100,
            'in_list' => true,
            'default_in_list' => false,
            'order'=>1,
            ),

    'order_create_date' => array(
      'type' => 'varchar(20)',
      'label' => '订单创建时间',
      'comment'=>'订单创建时间',
      'width' => 120,
      'in_list' => true,
      'default_in_list' => true,
      'order'=>16,
    ),
    'disabled' => array(
      'type' => 'bool',
      'required' => true,
      'default' => 'false',
      'editable' => false,
    ),
    'confirm_status' => array(
      'type' => array(
        '0' => '未对账',
        '1' => '已对账',
      ),
      'required' => true,
      'default' => '0',
      'label' => '与菜鸟的对账',
      'editable' => false,
      'in_list' => true,
      'default_in_list' => true,
      'order'=>20,
    ),
    'confirm_fail_msg' => array(
      'type' => 'varchar(255)',
      'required' => true,
      'default' => '',
      'label' => '对账失败原因',
      'editable' => false,
      'in_list' => true,
      'default_in_list' => true,
      'order'=>21,
    ),
    'split_status' => array(
      'type' => array(
        '0' => '未处理',
        '1' => '处理中',
        '2' => '不拆仅呈现',
        '3' => '拆分成功',
        '4' => '拆分失败',
        '5' => '无需拆分',
      ),
      'required' => true,
      'default' => '0',
      'label' => '拆分状态',
      'editable' => false,
      'in_list' => true,
      'default_in_list' => true,
      'order'=>25,
    ),
    'split_time' => array(
          'type' => 'time',
          'label' => '拆分时间',
          'editable' => false,
          'in_list' => false,
          'default_in_list' => false,
    ),
    'split_msg' => array(
          'type' => 'varchar(255)',
          'label' => '拆分失败原因',
          'editable' => false,
          'in_list' => true,
          'default_in_list' => true,
    ),
  ),
  'index' => array(
    'ind_shop_id' => array('columns' => array(0 => 'shop_id')),
    'ind_unique_id' => array('columns' => array(0 => 'unique_id')),
    'ind_trade_time' => array('columns' => array(0 => 'trade_time')),
    'ind_trade_no' => array('columns' => array(0 => 'trade_no')),
    'ind_order_bn' => array('columns' => array(0 => 'order_bn')),
    'ind_financial_no' => array('columns' => array(0 => 'financial_no')),
    'ind_platform_type' => array('columns' => array(0 => 'platform_type')),
    'ind_disabled' => array('columns' => array(0 => 'disabled')),
    'ind_bill_category' => array('columns' => array(0 => 'bill_category')),
    'ind_split_status' => array('columns' => array(0 => 'split_status')),
    'ind_split_time' => array('columns' => array(0 => 'split_time')),
   ),
  'comment' => '流水快速表',
  'engine' => 'innodb',
  'version' => '$Rev:  $',
);
