<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['queue'] = array(
    'columns' => array(
        'queue_id'    => array(
            'type'     => 'number',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'editable' => false,
        ),
        'queue_no' => array(
            'type'            => 'varchar(32)',
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'label'           => '队列号',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'width'           => 200,
            'order'           => 10,
            'searchtype'      => 'nequal',
        ),
        'queue_name'  => array(
            'type'            => 'varchar(200)',
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'label'           => '队列名',
            'is_title'        => true,
            'searchtype'      => 'has',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'width'           => 400,
            'order'           => 10,
        ),
        'queue_mode'  => array(
            'type'            => 'varchar(30)',
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'label'           => '队列模式',
            'default'         => 'import',
            'width'           => 100,
            'order'           => 15,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'searchtype'      => 'nequal',
        ),
        'status'      => array(
            'type'            => array(
                'ready'   => '准备处理',
                'process' => '检测中',
                'error'   => '未通过',
                'succ'    => '通过',
            ),
            'default'         => 'ready',
            'comment'         => '状态',
            'label'           => '状态',
            'in_list'         => true,
            'default_in_list' => true,
            'width'           => 100,
            'order'           => 50,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
        ),
        'is_file_ready' => array(
            'type'            => [
                '0' => '准备中',
                '1' => '已就绪',
                '2' => '已失效',
            ],
            'label'           => '文件是否就绪',
            'default'         => '1',
            'in_list'         => true,
            'default_in_list' => true,
            'width'           => 100,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
        ),
        'create_time' => array(
            'type'            => 'time',
            'comment'         => '上传时间',
            'label'           => '上传时间',
            'in_list'         => true,
            'default_in_list' => true,
            'width'           => 120,
            'order'           => 30,
            'filtertype'      => 'time',
            'filterdefault'   => true,
        ),
        'modify_time' => array(
            'type'            => 'time',
            'comment'         => '完成时间',
            'label'           => '完成时间',
            'in_list'         => true,
            'default_in_list' => true,
            'width'           => 120,
            'order'           => 40,
            'filtertype'      => 'time',
            'filterdefault'   => true,
        ),
        'queue_data'  => array(
            'type'  => 'longtext',
            'label' => '队列数据',
        ),
        'error_msg'   => array(
            'type'          => 'longtext',
            'label'         => '错误原因',
            'filtertype'    => 'normal',
            'filterdefault' => true,
        ),
        'disabled'    => array(
            'type'     => 'bool',
            'required' => true,
            'default'  => 'false',
            'editable' => false,
        ),
        'download_id' => array(
            'type'            => 'varchar(32)',
            'label'           => '下载ID',
            'default_in_list' => false,
            'in_list'         => true,
            'width'           => 200,
        ),
        'download_file' => array(
            'type'            => 'varchar(255)',
            'label'           => '下载URL',
            'default_in_list' => false,
            'in_list'         => true,
            'width'           => 200,
        ),
        'shop_id' =>
            array(
                'type'            => 'varchar(32)',
                'label'           => '来源店铺',
                'width'           => 75,
                'editable'        => false,
                'in_list'         => false,
                'default_in_list' => false,
            ),
        'retry_count' => array(
            'type'            => 'number',
            'label'           => '执行次数',
            'default'         => 0,
            'width'           => 80,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => false,
        ),
    ),
    'index'   => array(
        'ind_status'      => array('columns' => array(0 => 'status')),
        'ind_queue_name'  => array('columns' => array(0 => 'queue_name')),
        'ind_queue_mode'  => array('columns' => array('queue_mode', 'is_file_ready', 'status')),
        'ind_create_time' => array('columns' => array(0 => 'create_time')),
        'ind_modify_time' => array('columns' => array(0 => 'modify_time')),
        'ind_queue_no' 	  => array('columns' => array(0 => 'queue_no')),
        'ind_download_id' => array('columns' => array(0 => 'download_id')),
    ),
    'comment' => '队列表',
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
);
