<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['platform_orders'] = array(
    'columns' => array(
        'plat_order_id' => array(
            'pkey' => 'true',
            'type' => 'int unsigned',
            'extra' => 'auto_increment',
            'label' => '订单ID',
            'required' => true,
            'order' => 1,
        ),
        'plat_order_bn' => array(
            'type' => 'varchar(32)',
            'label' => '订单号',
            'editable' => true,
            'searchtype' => 'nequal',
            'filtertype' => 'normal',
            'filterdefault' => 'true',
            'in_list' => true,
            'default_in_list' => true,
            'width' => 180,
            'order' => 10,
        ),
        'shop_id' => array(
            'type' => 'table:shop@ome',
            'label' => '来源店铺',
            'editable' => false,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'width' => 110,
            'order' => 20,
        ),
        'shop_type' => array(
            'type' => 'varchar(50)',
            'label' => '店铺类型',
            'editable' => false,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'width' => 90,
            'order' => 22,
        ),
        'order_type' => array(
            'type' => array(
                'normal' => '订单',
                'sale' => '销售单',
                'presale' => '预售订单',
                'vopczc' => '唯品会仓中仓订单',
                'platform' => '平台发货',
                'offline' => '线下订单',
                'gift' => '礼品卡订单',
                'integral' => '积分订单',
                'exchange' => '换货订单',
                'brush' => '特殊订单',
                'jitxsc' => '唯品会省仓',
                'zerobuy' => '0元购',
                'bufa' => '补发订单',
            ),
            'default' => 'normal',
            'editable' => false,
            'label' => '订单类型',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 24,
        ),
        'convert_status' => array(
            'type' => array(
                'unconvert' => '未转单',
                'converted' => '已转单',
                'needless' => '无需转单',
                'splitting' => '部分转单',
                'fail' => '转单失败',
            ),
            'default' => 'unconvert',
            'editable' => false,
            'required' => true,
            'label' => '转单状态',
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 12,
        ),
        'dispose_status' => array(
            'type' => array(
                'zifa' => '自发',
                'all_daifa' => '全部代发',
                'part_daifa' => '部分代发',
                'fail' => '更新失败',
            ),
            'default' => 'zifa',
            'editable' => false,
            'label' => '发货方式',
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 13,
        ),
        'dispose_msg' => array(
            'type' => 'varchar(255)',
            'label' => '转换失败原因',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'width' => 280,
            'order' => 28,
        ),
        'ship_name' => array(
            'type' => 'varchar(255)',
            'label' => '收货人',
            'editable' => false,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 50,
        ),
        'ship_area' => array(
            'type' => 'region',
            'label' => '收货地区',
            'editable' => false,
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
            'width' => 180,
            'order' => 56,
        ),
        'ship_addr' => array(
            'type' => 'text',
            'label' => '收货地址',
            'editable' => false,
            'filtertype' => 'normal',
            'in_list' => true,
            'default_in_list' => false,
            'order' => 58,
        ),
        'ship_zip' => array(
            'label' => '收货邮编',
            'type' => 'varchar(20)',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'ship_tel' => array(
            'type' => 'varchar(200)',
            'label' => '收货人电话',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'ship_mobile' => array(
            'label' => '收货人手机',
            'type' => 'varchar(200)',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 52,
        ),
        'ship_email' => array(
            'type' => 'varchar(150)',
            'editable' => false,
            'label' => '收货人邮箱',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'ship_time' => array(
            'type' => 'varchar(50)',
            'editable' => false,
            'label' => '要求到货时间',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'member_id' => array(
            'type' => 'table:members@ome',
            'label' => '会员用户名',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 60,
        ),
        'oaid' => array(
            'type' => 'varchar(200)',
            'editable' => false,
            'label' => '地址唯一标识',
            'in_list' => false,
            'default_in_list' => false,
        ),
        'status' => array(
            'type' => array(
                'active' => '活动订单',
                'dead' => '已作废',
                'finish' => '已完成',
            ),
            'default' => 'active',
            'editable' => false,
            'label' => '订单状态',
            'in_list' => false,
            'default_in_list' => false,
            'width' => 90,
            'order' => 19,
        ),
        'process_status' => array(
            'type' => array(
                'unconfirmed' => '未确认',
                'confirmed' => '已确认',
                'splitting' => '部分拆分',
                'splited' => '已拆分完',
                'cancel' => '取消',
            ),
            'default' => 'unconfirmed',
            'editable' => false,
            'required' => true,
            'label' => '确认状态',
            'in_list' => false,
            'default_in_list' => false,
            'order' => 20,
        ),
        'source_status' => array(
            'type' => 'varchar(64)',
            'label' => '平台状态',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'source' => array(
            'type' => 'varchar(50)',
            'default' => 'matrix',
            'editable' => false,
            'label' => '订单来源',
            'comment' => '订单来源,可选值:matrix(矩阵),local(本地),import(导入),after(售后)',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 70,
        ),
        'order_source' => array(
            'type' => 'varchar(50)',
            'label' => '来源渠道',
            'default' => 'direct',
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 72,
        ),
        'pay_status' => array(
            'type' => array(
                0 => '未支付',
                1 => '已支付',
                2 => '处理中',
                3 => '部分付款',
                4 => '部分退款',
                5 => '全额退款',
                6 => '退款申请中',
                7 => '退款中',
                8 => '支付中',
            ),
            'default' => '0',
            'editable' => false,
            'required' => true,
            'label' => '付款状态',
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 14,
        ),
        'ship_status' => array(
            'type' => array(
                0 => '未发货',
                1 => '已发货',
                2 => '部分发货',
                3 => '部分退货',
                4 => '已退货',
            ),
            'default' => '0',
            'editable' => false,
            'required' => true,
            'label' => '发货状态',
            'in_list' => true,
            'default_in_list' => false,
            'order' => 16,
        ),
        'is_delivery' => array(
            'type' => 'tinybool',
            'default' => 'Y',
            'required' => true,
            'editable' => false,
            'label' => '是否可以发货',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'pay_bn' => array(
            'type' => 'varchar(50)',
            'editable' => false,
            'label' => '支付编号',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'payment' => array(
            'type' => 'varchar(30)',
            'label' => '支付方式',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'shipping_name' => array(
            'type' => 'varchar(30)',
            'label' => '配送方式',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'cost_freight' => array(
            'type' => 'money',
            'default' => '0',
            'required' => true,
            'label' => '配送费用',
            'editable' => false,
            'filtertype' => 'number',
            'in_list' => true,
        ),
        'is_cod' => array(
            'type' => 'bool',
            'default' => 'false',
            'editable' => false,
            'label' => '货到付款',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'pmt_goods' => array(
            'type' => 'money',
            'default' => '0',
            'required' => true,
            'editable' => false,
            'label' => '商品优惠',
            'in_list' => true,
            'default_in_list' => false,
            'order' => 44,
        ),
        'pmt_order' => array(
            'type' => 'money',
            'default' => '0',
            'required' => true,
            'editable' => false,
            'label' => '订单优惠',
            'in_list' => true,
            'default_in_list' => false,
            'order' => 42,
        ),
        'total_amount' => array(
            'type' => 'money',
            'default' => 0,
            'label' => '订单总额',
            'editable' => false,
            'filtertype' => 'number',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 40,
        ),
        'final_amount' => array(
            'type' => 'money',
            'default' => 0,
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
        ),
        'payed' => array(
            'type' => 'money',
            'default' => '0',
            'editable' => false,
            'label' => '已支付金额',
            'in_list' => true,
            'default_in_list' => false,
            'order' => 45,
        ),
        'cost_item' => array(
            'type' => 'money',
            'default' => '0',
            'editable' => false,
            'label' => '商品金额',
            'required' => true,
            'in_list' => true,
            'order' => 48,
        ),
        'is_abnormal' => array(
            'type' => 'bool',
            'default' => 'false',
            'editable' => false,
            'label' => '是否异常',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'abnormal_status' => array(
            'type' => 'bigint(20)',
            'default' => 0,
            'label' => '异常状态标识位',
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
        ),
        'pause' => array(
            'type' => 'bool',
            'default' => 'false',
            'editable' => false,
            'label' => '是否暂停',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'logi_type' => array(
            'type' => 'varchar(20)',
            'label' => '物流公司',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
        ),
        'logi_no' => array(
            'type' => 'varchar(50)',
            'label' => '物流单号',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'textarea',
            'filterdefault' => true,
            'width' => 120,
        ),
        'splited_num' => array(
            'label' => '拆单次数',
            'type' => 'number',
            'editable' => false,
            'filtertype' => 'yes',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'itemnum' => array(
            'type' => 'number',
            'editable' => false,
            'label' => '订单明细数量',
            'in_list' => true,
            'default_in_list' => false,
        ),
        'encrypt_data' => array(
            'type' => 'text',
            'label' => '密文数据',
            'editable' => false,
            'in_list' => false,
            'default_in_list' => false,
        ),
        'paytime' => array(
            'type' => 'time',
            'label' => '付款时间',
            'editable' => false,
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 90,
        ),
        'delivery_time' => array(
            'type' => 'time',
            'label' => '发货时间',
            'editable' => false,
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 94,
        ),
        'download_time' => array(
            'type' => 'time',
            'label' => '订单下载时间',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 92,
        ),
        'outer_lastmodify' => array(
            'label' => '平台更新时间',
            'type' => 'time',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 95,
        ),
        'up_time' => array(
            'type' => 'time',
            'label' => '订单回传时间',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'order' => 96,
        ),
        'createtime' => array(
            'type' => 'time',
            'label' => '下单时间',
            'editable' => false,
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 98,
        ),
        'last_modified' => array(
            'label' => '最后更新时间',
            'type' => 'last_modify',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 99,
        ),
        'bs_id' => array(
            'type' => 'int(10)',
            'default' => 0,
            'editable' => false,
            'label' => '经销商ID',
            'in_list' => false,
            'default_in_list' => false,
        ),
        'cos_id' => array(
            'type' => 'varchar(255)',
            'default' => 0,
            'editable' => false,
            'label' => '组织架构ID',
            'in_list' => false,
            'default_in_list' => false,
        ),
        'timing_confirm' => array(
            'type' => 'time',
            'label' => '定时审单订单',
            'default' => 0,
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => false,
        ),
        'is_fail' => array(
            'type' => 'bool',
            'required' => true,
            'default' => 'false',
            'editable' => false,
            'label' => '失败订单',
        ),
        'edit_status' => array(
            'type' => 'bool',
            'required' => true,
            'default' => 'false',
            'editable' => false,
            'comment' => '订单编辑状态,可选值:true(是),false(否)'
        ),
        'is_modify' => array(
            'type' => 'bool',
            'label' => '商品信息编辑',
            'default' => 'false',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => false,
            'width' => 90,
            'comment' => '订单是否修改过商品信息,可选值:true(是),false(否)',
        ),
    ),
    'index' => array(
        'uni_order_shop' => array(
            'columns' => array(
                0 => 'plat_order_bn',
                1 => 'shop_id',
            ),
            'prefix' => 'unique',
        ),
        'ind_shop_type' => array(
            'columns' => array(
                0 => 'shop_type',
            ),
        ),
        'ind_convert_status' => array(
            'columns' => array(
                0 => 'convert_status',
                1 => 'status',
                2 => 'is_fail',
            ),
        ),
        'ind_dispose_fail' => array(
            'columns' => array(
                0 => 'dispose_status',
                1 => 'status',
                2 => 'is_fail',
            ),
        ),
        'ind_status' => array(
            'columns' => array(
                0 => 'status',
            ),
        ),
        'ind_ship_status' => array(
            'columns' => array(
                0 => 'ship_status',
            ),
        ),
        'ind_pay_status' => array(
            'columns' => array(
                0 => 'pay_status',
            ),
        ),
        'ind_paytime' => array(
            'columns' => array(
                0 => 'paytime',
            ),
        ),
        'ind_delivery_time' => array(
            'columns' => array(
                0 => 'delivery_time',
            ),
        ),
        'ind_download_time' => array(
            'columns' => array(
                0 => 'download_time',
            ),
        ),
        'ind_createtime' => array(
            'columns' => array(
                0 => 'createtime',
            ),
        ),
        'ind_bs_id' => array(
            'columns' => array(
                0 => 'bs_id',
            ),
        ),
        'ind_cos_id' => array(
            'columns' => array(
                0 => 'cos_id',
            ),
        ),
        'ind_timing_confirm' => array(
            'columns' => array(
                0 => 'timing_confirm',
            ),
        ),
        'ind_is_fail' => array(
            'columns' => array(
                0 => 'is_fail',
            ),
        ),
        'ind_is_abnormal' => array(
            'columns' => array(
                0 => 'is_abnormal',
            ),
        ),
    ),
    'engine' => 'innodb',
    'version' => '$Rev: $',
    'comment' => '分销平台订单主表',
);