<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['pick_bill_check_items'] = array(
    'columns' => array(
        'check_item_id'         => array(
            'type'     => 'int unsigned',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'editable' => false,
        ),
        'bill_id'               => array(
            'type'     => 'table:pick_bills@purchase',
            'default'  => 0,
            'label'    => '拣货单编号',
            'editable' => false,
        ),
        'bill_item_id'          => array(
            'type'     => 'table:pick_bill_items@purchase',
            'default'  => 0,
            'editable' => false,
        ),
        'bn'                    => array(
            'type'     => 'varchar(30)',
            'label'    => '货号',
            'width'    => 100,
            'editable' => false,
        ),
        'barcode'               => array(
            'type'     => 'varchar(80)',
            'label'    => '条码',
            'width'    => 100,
            'editable' => false,
        ),
        'channel'               => array(
            'type'            => 'varchar(32)',
            'label'           => '会员反馈途径',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'problem_desc'          => array(
            'type'            => 'varchar(32)',
            'label'           => '问题描述',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'order_label'           => array(
            'type'            => 'varchar(32)',
            'label'           => '订单标签', // 0-未知，1-普通订单，2-原订单，3-一换订单，4-二换订单
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'image_fileid_list'     => array(
            'type'            => 'varchar(255)',
            'label'           => '图片信息',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'image_list'            => array(
            'type'            => 'varchar(255)',
            'label'           => '图片信息',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'video_fileid_list'     => array(
            'type'            => 'varchar(255)',
            'label'           => '视频信息',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'video_list'            => array(
            'type'            => 'varchar(255)',
            'label'           => '视频信息',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'delivery_warehouse'    => array(
            'type'            => 'varchar(32)',
            'label'           => '发货仓',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'order_sn'              => array(
            'type'            => 'varchar(32)',
            'label'           => '订单号',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'first_classification'  => array(
            'type'            => 'varchar(64)',
            'label'           => '一级分类',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'second_classification' => array(
            'type'            => 'varchar(64)',
            'label'           => '二级分类',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'third_classification'  => array(
            'type'            => 'varchar(64)',
            'label'           => '三级分类',
            'width'           => 180,
            'searchtype'      => 'nequal',
            'editable'        => false,
            'filtertype'      => 'textarea',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => false,
        ),
        'at_time'               => array(
            'type'    => 'TIMESTAMP',
            'label'   => '创建时间',
            'default' => 'CURRENT_TIMESTAMP',
            'width'   => 120,
            'in_list' => false,
            'order'   => 11,
        ),
        'up_time'               => array(
            'type'    => 'TIMESTAMP',
            'label'   => '更新时间',
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'width'   => 120,
            'in_list' => false,
        ),
    ),
    'index'   => array(
        'ind_bill_id'      => array(
            'columns' => array(
                0 => 'bill_id',
            ),
        ),
        'ind_bill_item_id' => array(
            'columns' => array(
                0 => 'bill_item_id',
            ),
        ),
        'ind_bn'           => array(
            'columns' => array(
                0 => 'bn',
            ),
        ),
        'ind_barcode'      => array(
            'columns' => array(
                0 => 'barcode',
            ),
        ),
    ),
    'engine'  => 'innodb',
    'version' => '$Rev: 40912 $',
    'comment' => '拣货单明细检测表',
);
