<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['queue'] = array(
    'columns' => array(
        'queue_id'    => array(
            'type'     => 'number',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'editable' => false,
        ),
        'queue_no'    => array(
            'type'            => 'varchar(32)',
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'label'           => '队列号',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'width'           => 120,
            'order'           => 10,
            'searchtype'      => 'nequal',
        ),
        'queue_name'  => array(
            'type'            => 'varchar(200)',
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'label'           => '队列名',//文件名+任务
            'is_title'        => true,
            'searchtype'      => 'has',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'width'           => 200,
            'order'           => 15,
        ),
        'queue_mode'  => array(
            'type'            => 'varchar(30)',
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'label'           => '队列模式',
            'default'         => 'import',
            'width'           => 100,
            'order'           => 20,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'searchtype'      => 'nequal',
        ),
        'status'      => array(
            'type'            => array(
                'ready'   => '准备处理',
                'process' => '检测中',
                'error'   => '未通过',
                'succ'    => '通过',
                'partsucc'=> '部分通过',
            ),
            'default'         => 'ready',
            'comment'         => '状态',
            'label'           => '状态',
            'in_list'         => true,
            'default_in_list' => true,
            'width'           => 80,
            'order'           => 50,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
        ),
        'create_time' => array(
            'type'            => 'time',
            'comment'         => '上传时间',
            'label'           => '上传时间',
            'in_list'         => true,
            'default_in_list' => true,
            'width'           => 130,
            'order'           => 30,
            'filtertype'      => 'time',
            'filterdefault'   => true,
        ),
        'modify_time' => array(
            'type'            => 'time',
            'comment'         => '完成时间',
            'label'           => '完成时间',
            'in_list'         => true,
            'default_in_list' => true,
            'width'           => 130,
            'order'           => 40,
            'filtertype'      => 'time',
            'filterdefault'   => true,
        ),
        'queue_data'  => array(
            'type'  => 'longtext',
            'label' => '队列数据',
        ),
        'error_msg'   => array(
            'type'          => 'longtext',
            'label'         => '错误原因',
            'filtertype'    => 'normal',
            'filterdefault' => true,
            'in_list'         => true,
            'default_in_list' => true,
            'width'           => 200,
            'order'           => 100,
        ),
        'disabled'    => array(
            'type'     => 'bool',
            'required' => true,
            'default'  => 'false',
            'editable' => false,
        ),
        'split_count' =>
            array(
                'type'            => 'number',
                'label'           => '数据条数',
                'default'         => '0',
                'width'           => 70,
                'editable'        => false,
                'in_list'         => true,
                'default_in_list' => true,
                'order'           => 70,
            ),
        'parent_id'   =>
            array(
                'type'            => 'number',
                'label'           => '分类ID',
                'width'           => 110,
                'editable'        => false,
                'in_list'         => false,
                'default_in_list' => false,
            ),
        'original_bn' => array(
            'type'            => 'varchar(64)',
            'label'           => '外部单号',
            'default_in_list' => true,
            'in_list'         => true,
            'width'           => 130,
            'order'           => 80,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'searchtype'      => 'nequal',
        ),
        'original_id' => array(
            'type'    => 'int unsigned',
            'comment' => '原始单据id',
        ),
        'at_time'     =>
            array(
                'type'    => 'TIMESTAMP',
                'label'   => '创建时间',
                'default' => 'CURRENT_TIMESTAMP',
                'width'   => 120,
                'in_list' => false,
                'order'   => 120,
            ),
        'up_time'     =>
            array(
                'type'    => 'TIMESTAMP',
                'label'   => '更新时间',
                'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
                'width'   => 120,
                'in_list' => false,
                'order'   => 130,
            ),
        'bill_type' => array(
            'type'            => 'varchar(35)',
            'label'           => '业务类型',
            'default_in_list' => true,
            'in_list'         => true,
            'searchtype'      => 'has',
            'order'           => 60,
            'width'           => 80,
        ),
        'remote_url' => array(
            'type'            => 'varchar(255)',
            'label'           => '文件名',
            'default_in_list' => false,
            'in_list'         => true,
            'order'           => 90,
            'width'           => 100,
        ),
    ),
    'index'   => array(
        'ind_status'      => array('columns' => array(0 => 'status')),
        'ind_queue_name'  => array('columns' => array(0 => 'queue_name')),
        'ind_queue_mode'  => array('columns' => array(0 => 'queue_mode')),
        'ind_create_time' => array('columns' => array(0 => 'create_time')),
        'ind_modify_time' => array('columns' => array(0 => 'modify_time')),
        'ind_queue_no'    => array('columns' => array(0 => 'queue_no')),
    ),
    'comment' => '队列表',
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
);
