<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['store'] = array(
    'columns' => array(
        'store_id'      => array(
            'type'     => 'int unsigned',
            'required' => true,
            'width'    => 110,
            'hidden'   => true,
            'editable' => false,
            'pkey'     => true,
            'extra'    => 'auto_increment',
        ),
        'store_bn'      => array(
            'type'     => 'varchar(20)',
            'required' => true,
            'label'    => '门店编码',
            'editable' => false,
            'searchtype' => 'nequal',
            'filtertype' => 'normal',
            'filterdefault' => true,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'name'          => array(
            'type'     => 'varchar(255)',
            'required' => true,
            'label'    => '门店名称',
            'editable' => false,
            'is_title' => true,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'server_id'     => array(
            'type'     => 'number',
            'required' => true,
            'editable' => false,
            'label'    => '服务端ID',
        ),
        'branch_id'     => array(
            'type'     => 'number',
            'editable' => false,
            'label'    => '虚拟仓ID',
        ),
        'shop_id'       => array(
            'type'     => 'varchar(32)',
            'editable' => false,
            'label'    => '店铺ID',
        ),
        'open_hours'    => array(
            'type'     => 'varchar(20)',
            'label'    => '营业时间',
            'editable' => false,
        ),
        'area'          => array(
            'type'     => 'region',
            'label'    => '地区',
            'editable' => false,
            // 'filtertype'    => 'yes',
            // 'filterdefault' => true,
            'in_list'       => true,
        ),
        'addr'          => array(
            'type'            => 'varchar(255)',
            'required'        => true,
            'label'           => '详细地址',
            'width'           => 200,
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 4,
        ),
        'longitude'     => array(
            'type'  => 'varchar(30)',
            'label' => '经度',
            'width' => 150,
        ),
        'latitude'      => array(
            'type'  => 'varchar(30)',
            'label' => '纬度',
            'width' => 150,
        ),
        'fax'           => array(
            'type'            => 'varchar(20)',
            'label'           => '传真',
            'width'           => 110,
            'editable'        => false,
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'zip'           => array(
            'type'            => 'varchar(20)',
            'required'        => true,
            'editable'        => false,
            'label'           => '邮编',
            'width'           => 100,
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 5,
        ),
        'contacter'     => array(
            'type'            => 'varchar(255)',
            'required'        => true,
            'editable'        => false,
            'label'           => '联系人',
            'width'           => 100,
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 6,
        ),
        'mobile'        => array(
            'type'            => 'varchar(30)',
            'required'        => false,
            'editable'        => false,
            'label'           => '手机',
            'width'           => 100,
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 7,
        ),
        'tel'           => array(
            'type'            => 'varchar(30)',
            'required'        => false,
            'editable'        => false,
            'label'           => '固定电话',
            'width'           => 100,
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 8,
        ),
        'store_type'    => array(
            'type'     => 'varchar(20)',
            'required' => true,
            'editable' => false,
            'label'    => '经营模式',
            'default'  => 'self',
        ),
        'self_pick'     => array(
            'type'     => 'tinyint(1)',
            'required' => true,
            'editable' => false,
            'label'    => '自提',
            'default'  => 2,
        ),
        'distribution'  => array(
            'type'     => 'tinyint(1)',
            'required' => true,
            'editable' => false,
            'label'    => '配送',
            'default'  => 2,
        ),
        'aftersales'    => array(
            'type'     => 'tinyint(1)',
            'required' => true,
            'editable' => false,
            'label'    => '门店售后',
            'default'  => 2,
        ),
        'confirm'       => array(
            'type'     => 'tinyint(1)',
            'required' => true,
            'editable' => false,
            'label'    => '订单回执确认',
            'default'  => 2,
        ),
        'is_ctrl_store' => array(
            'type'     => 'tinyint(1)',
            'required' => true,
            'editable' => false,
            'label'    => '管控库存',
            'default'  => 1,
            'comment'  => '管控库存(1=是，2=否)',
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'status'        => array(
            'type'            => 'tinyint(1)',
            'label'           => '状态',
            'width'           => 80,
            'default'         => 2,
            'in_list'         => true,
            'default_in_list' => true,
            'order'           => 10,
        ),
        'create_time'   => array(
            'type'     => 'time',
            'label'    => '创建时间',
            'width'    => 130,
            'editable' => false,
            'in_list'  => true,
        ),
        'last_modified' => array(
            'label'    => '更新时间',
            'type'     => 'last_modify',
            'width'    => 130,
            'editable' => false,
            'in_list'  => true,
        ),
        'source'        => array(
            'type'     => 'varchar(30)',
            'editable' => false,
            'label'    => '来源',
            'width'    => 100,
            'in_list'  => true,
            'default'  => 'local',
            'comment'  => 'local:本地,sap:SAP,openapi:openapi',
        ),
        'priority'      => array(
            'type'            => 'int(10)',
            'default'         => 0,
            'label'           => '优先级',
            'default_in_list' => true,
            'in_list'         => true,
        ),
        'store_mode' => array (
            'label' => '门店销售类型',
            'type' => array (
                'normal' => '正价店铺',
                'discount' => '奥莱店铺',
            ),
            'default' => 'normal',
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
        ),
        'is_negative_store' => array(
            'type'     => 'tinyint(1)',
            'editable' => false,
            'label'    => '允许负库存',
            'default'  => 2,
            'comment'  => '允许负库存(1=是，2=否)',
            'in_list'         => true,
            'default_in_list' => true,
        ),
        'is_o2o' => array(
            'type'     => 'tinyint(1)',
            'editable' => false,
            'label'    => '是否参加O2O',
            'default'  => 1,
            'comment'  => '是否参加O2O(1=是，2=否)',
            'in_list'         => true,
            'default_in_list' => true,
        ),
    ),
    'index'   => array(
        'ind_server_id'     => array('columns' => array('server_id')),
        'ind_branch_id'     => array('columns' => array('branch_id')),
        'ind_create_time'   => array('columns' => array('create_time')),
        'ind_last_modified' => array('columns' => array('last_modified')),
    ),
    'comment' => '组织架构门店属性表',
    'engine'  => 'innodb',
);
