<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['adjust'] = array(
    'columns' => array(
        'id'        => array(
            'type'     => 'int unsigned',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'label'    => 'ID',
            'width'    => 110,
            'hidden'   => true,
            'editable' => false,
        ),
        'adjust_bn'        => array(
            'type'            => 'varchar(255)',
            'label'           => '调整单单号',
            'default_in_list' => true,
            'searchtype'      => 'nequal',
            'in_list'         => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'order' => 10,
            'width'           => 200,
        ),
        'adjust_type'      => array(
            'type'            => array(
                'tz' => '调帐',
                'yd' => '异动',
                'cy' => '差异',
                'pd' => '盘点',
            ),
            'label'           => '调整单类型',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'default'        => 'tz',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 20,
        ),
        'adjust_channel'      => array(
            'type'            => 'varchar(25)',
            'label'           => '调整单类型',
            'comment'         => '调整单类型,branchadjust:仓库，storeadjust:门店',
            // 'filtertype'      => 'normal',
            // 'filterdefault'   => true,
            'default'        => 'branchadjust',
            // 'default_in_list' => true,
            // 'in_list'         => true,
            // 'order' => 20,
        ),
        'adjust_bill_type'      => array(
            'type'            => 'varchar(255)',
            'label'           => '调整单子类型',
            'default'        => '',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 23,
        ),
        'adjust_mode'      => array(
            'type'            => array(
                'zl' => '增量',
                'ql' => '全量',
            ),
            'label'           => '调整方式',
            'default'        => 'zl',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 25,
        ),
      
        'branch_id'        => array(
            'type'            => 'table:branch@ome',
            'required'        => true,
            'label'           => '仓库名称',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 30,
        ),
        'negative_branch_id' =>
        array (
          'type' => 'text',
          'in_list' => true,
          'default_in_list' => true,
          'label' => '出库仓库',
        ),
        'bill_status'       => array(
            'type'          => array(
                1 => '新建',
                2 => '确认中',
                3 => '取消',
                4 => '完成',
             ),
            'default'       => 1,
            'label'         => '单据状态',
            'width'         => 90,
            'editable'      => false,
            'in_list'         => true,
            'default_in_list' => true,
            'filtertype'    => 'normal',
            'filterdefault' => true,
            'order' => 28,
        ),
        'is_check'       => array(
            'type'          => array(
                '0' => '否',
                '1' => '是',
             ),
            'default'       => '0',
            'label'         => '财务审核',
            'width'         => 90,
            'editable'      => false,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 28,
        ),
        'iso_status'       => array(
            'type'          => array(
                'check' => '审核',
                'confirm' => '完成',
             ),
            'default'       => 'check',
            'label'         => '同步wms',
            'width'         => 90,
            'editable'      => false,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 28,
        ),
        'operator'       => array(
            'type'            => 'varchar(30)',
            'default_in_list' => true,
            'in_list'         => true,
            'label'           => '操作人员',
            'order' => 90,
        ),
        'origin_id'       => array(
            'type'            => 'int',
            'default_in_list' => false,
            'in_list'         => false,
            'label'           => '来源ID',
            'order' => 90,
        ),
        'origin_bn'       => array(
            'type'            => 'varchar(255)',
            'default_in_list' => true,
            'in_list'         => true,
            'label'           => '来源单号',
            'order' => 90,
        ),
        'business_bn'       => array(
            'type'            => 'varchar(255)',
            'default_in_list' => true,
            'in_list'         => true,
            'label'           => '业务单号',
            'order' => 90,
        ),
        'memo'       => array(
            'type'            => 'varchar(255)',
            'default_in_list' => true,
            'in_list'         => true,
            'searchtype'      => 'has',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'label'           => '单据备注',
            'order' => 90,
        ),
        
        'source' => array(
            'type'            => 'varchar(20)',
            'default'           => 'wms',
            'label'             => '来源',
            'in_list'           => true,
            'default_in_list'   => true,
            'order'             => 100,
        ),
        'at_time'       => array(
            'type'            => 'TIMESTAMP',
            'label'           => '创建时间',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'time',
            'filterdefault'   => true,
            'default'         => 'CURRENT_TIMESTAMP',
            'order' => 100,
        ),
        'up_time'       => array(
            'type'            => 'TIMESTAMP',
            'label'           => '更新时间',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'time',
            'filterdefault'   => true,
            'default'         => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'order' => 110,
        ),
    ),
    'index'   => array(
        'idx_adjust_bn'   => array('columns' => array('adjust_bn'), 'prefix' => 'UNIQUE'),
        'idx_origin_id'   => array('columns' => array('origin_id')),
        'idx_business_bn'   => array('columns' => array('business_bn')),
        'idx_adjust_channel'   => array('columns' => array('adjust_channel')),
        'idx_at_time'       => array('columns' => array('at_time')),
        'idx_up_time'       => array('columns' => array('up_time')),
    ),
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
    'comment' => '库存调整表',
);
