<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['cpfr'] = array(
    'columns' => array(
        'cpfr_id'        => array(
            'type'     => 'int unsigned',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'label'    => 'ID',
            'width'    => 110,
            'hidden'   => true,
            'editable' => false,
        ),
        'cpfr_bn'        => array(
            'type'            => 'varchar(30)',
            'label'           => '配货单编码',
            'comment'         => '配货单编码',
            'required'        => true,
            'default_in_list' => true,
            'in_list'         => true,
            'searchtype'      => 'head',
            'order' => 10,
            'width'           => 200,
        ),
        'cpfr_name'      => array(
            'type'            => 'varchar(50)',
            'label'           => '配货单名称',
            'comment'         => '配货单名称',
            'required'        => true,
            'default_in_list' => true,
            'in_list'         => true,
            'searchtype'      => 'head',
            'order' => 20,
        ),
        'branch_id'        => array(
            'type'            => 'table:branch@ome',
            'required'        => true,
            'label'           => '调出仓库',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 30,
        ),
        'branch_bn'      => array(
            'type'            => 'varchar(32)',
            'label'           => '调出仓库编码',
            'default_in_list' => true,
            'in_list'         => true,
            'searchtype'      => 'nequal',
            'order' => 32,
        ),
        'store_total'    => array(
            'type'            => 'number',
            'label'           => '门店总数',
            'comment'         => '门店总数',
            'default'         => 0,
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 50,
        ),
        'sku_total'      => array(
            'type'            => 'number',
            'label'           => 'SKU总数',
            'comment'         => 'SKU总数',
            'default'         => 0,
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 52,
        ),
        'num_total'      => array(
            'type'            => 'number',
            'label'           => '申请总数量',
            'comment'         => '申请总数量',
            'default'         => 0,
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 54,
        ),
        'actual_total'      => array(
            'type'            => 'number',
            'label'           => '实际补货总数',
            'default'         => 0,
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 56,
        ),
        'original_total' => array(
            'type'            => 'number',
            'label'           => '导入数量',
            'comment'         => '导入数量',
            'default'         => 0,
            'editable'        => false,
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 58,
        ),
        'bill_status'       => array(
            'type'          => array(
                1 => '未完成',
                2 => '完成',
             ),
            'default'       => 1,
            'label'         => '单据状态',
            'width'         => 90,
            'editable'      => false,
            'in_list'         => true,
            'default_in_list' => true,
            'filtertype'    => 'has',
            'filterdefault' => true,
            'order' => 28,
        ),
        'operator'       => array(
            'type'            => 'varchar(30)',
            'comment'         => '操作人员',
            'default_in_list' => true,
            'in_list'         => true,
            'label'           => '操作人员',
            'order' => 90,
        ),
        'adjust_type'       => array(
            'type'          => array(
                'manual' => '手动调整',
                'import' => '导入调整',
                'replenish' => '补货任务',
            ),
            'default'       => 'import',
            'label'         => '调整库存类型',
            'width'         => 90,
            'editable'      => false,
            'in_list'         => true,
            'default_in_list' => true,
            'filtertype'    => 'has',
            'filterdefault' => true,
            'order' => 80,
        ),
        'update_type'       => array(
            'type'          => array(
                'inc' => '增量',
                'all' => '全量',
            ),
            'default'       => 'all',
            'label'         => '库存更新方式',
            'width'         => 90,
            'editable'      => false,
            'in_list'         => false,
            'default_in_list' => false,
            'filtertype'    => 'has',
            'filterdefault' => true,
            'order' => 82,
        ),
        'origin_bn' => array(
            'type' => 'varchar(30)',
            'label' => '补货任务号',
            'searchtype' => 'nequal',
            'default_in_list' => true,
            'in_list' => true,
            'width' => 200,
            'order' => 29,
        ),
        'create_time' => array(
            'type' => 'time',
            'label' => '创建时间',
            'in_list' => true,
            'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'time',
            'filterdefault' => true,
            'order' => 98,
        ),
        'last_modified' => array(
            'label' => '最后更新时间',
            'type' => 'last_modify',
            'width' => 130,
            'editable' => false,
            'in_list'  => true,
            'default_in_list' => true,
            'order' => 99,
        ),
    ),
    'index'   => array(
        'idx_cpfr_bn'   => array('columns' => array('cpfr_bn'), 'prefix' => 'UNIQUE'),
        'idx_cpfr_name' => array('columns' => array('cpfr_name')),
        'idx_origin_bn' => array('columns' => array('origin_bn')),
       
        'idx_time_adjusttype' => array(
                'columns' => array(
                    0 => 'create_time',
                    1 => 'adjust_type',
                ),
        ),
    ),
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
    'comment' => '配货单表',
);
