<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['replenish_diff'] = array(
    'columns' => array(
        'diff_id' => array(
            'type' => 'int unsigned',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
            'label' => 'ID',
            'width' => 110,
            'hidden' => true,
            'editable' => false,
        ),
        'task_bn' => array(
            'type' => 'varchar(30)',
            'label' => '补货任务号',
            'required' => true,
            'default_in_list' => true,
            'in_list' => true,
            'searchtype' => 'nequal',
            'filtertype' => 'normal',
            'filterdefault' => true,
            'width' => 200,
            'order' => 10,
        ),
        'cpfr_bn' => array(
            'type' => 'varchar(30)',
            'label' => '配货单编码',
            'required' => true,
            'default_in_list' => true,
            'in_list' => true,
            'searchtype' => 'head',
            'order' => 10,
            'width' => 200,
        ),
        'store_bn' => array(
            'type' => 'varchar(20)',
            'required' => true,
            'label' => '门店编码',
            'editable' => false,
            'searchtype' => 'nequal',
            'filtertype' => 'normal',
            'filterdefault' => true,
            'default_in_list' => true,
            'in_list' => true,
            'width' => 120,
            'order' => 20,
        ),
        'out_branch_id' => array(
            'type' => 'table:branch@ome',
            'required' => true,
            'label' => '调出仓库',
            'filtertype' => 'normal',
            'filterdefault'   => true,
            'default_in_list' => true,
            'in_list' => true,
            'order' => 30,
        ),
        'to_branch_id' => array(
            'type' => 'table:branch@ome',
            'label' => '调入仓库',
            'filtertype' => 'normal',
            'filterdefault' => true,
            'default_in_list' => true,
            'in_list' => true,
            'order' => 31,
        ),
        'product_id' => array(
            'type' => 'int unsigned',
            'required' => true,
            'width'    => 110,
            'hidden'   => true,
            'editable' => false,
        ),
        'material_bn' => array (
          'type' => 'varchar(30)',
          'label' => '基础物料编码',
          'width' => 140,
          'editable' => false,
          'in_list' => true,
          'default_in_list' => true,
          'required' => true,
          'searchtype' => 'nequal',
          'filtertype' => 'textarea',
          'filterdefault' => true,
          'order' => 35,
        ),
        'apply_nums' => array (
            'type' => 'number',
            'editable' => false,
            'label' => '申请补货数量',
            'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 41,
        ),
        'finish_nums' => array (
            'type' => 'number',
            'editable' => false,
            'label' => '最终补货数量',
            'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 42,
        ),
        'not_nums' => array (
            'type' => 'number',
            'editable' => false,
            'label' => '未补货数量',
            'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 43,
        ),
        'create_time' => array(
            'type' => 'time',
            'label' => '创建时间',
            'in_list' => true,
            'default' => 0,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 98,
        ),
    ),
    'index' => array(
        'in_cpfr_bn' => array(
            'columns' => array('cpfr_bn'),
        ),
        'in_task_bn' => array(
            'columns' => array('task_bn'),
        ),
        'in_store_bn' => array(
            'columns' => array('store_bn'),
        ),
        'in_material_bn' => array(
            'columns' => array('material_bn'),
        ),
        'in_create_time' => array(
            'columns' => array('create_time'),
        ),
    ),
    'engine'  => 'innodb',
    'version' => '$Rev: $',
    'comment' => '补货差异单据表',
);
