<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['vopreturn'] = array(
    'columns' => array(
        'id'                => array(
            'type'     => 'int unsigned',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'label'    => '主键id',
            'editable' => false,
        ),
        'return_sn'         => array(
            'type'            => 'varchar(255)',
            'label'           => '退供单号',
            'is_title'        => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 1,
            'searchtype' => 'nequal',
        ),
        'status'            => array(
            'type'            => [
                '0' => '待获取',
                '1' => '已确认',
                '2' => '已完成',
                '3' => '已取消',
                '4' => '部分确认',
            ],
            'label'           => '单据状态',
            'default'         => '0',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 10,
            'filtertype'        => 'normal',
            'filterdefault'     => true,
        ),
        'in_status'            => array(
            'type'            => [
                '1' => '未入库',
                '2' => '部分入库',
                '3' => '已入库',
            ],
            'label'           => '入库状态',
            'default'         => '1',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 15,
        ),
        'shop_id'           => array(
            'type'            => 'table:shop@ome',
            'label'           => '店铺',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 20,
            'filtertype' => 'normal',
        ),
        'shop_type' =>
        array (
            'type' => 'varchar(50)',
            'label' => '店铺类型',
            'width' => 75,
            'editable' => false,
            'in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
        ),
        'total_qtys'        => array(
            'type'            => 'number',
            'label'           => '总商品数',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 30,
        ),
        'total_skus'        => array(
            'type'            => 'number',
            'label'           => '总商品条码数',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 40,
        ),
        'total_cases'       => array(
            'type'            => 'number',
            'label'           => '总箱数',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 50,
        ),
        'warehouse'         => array(
            'type'            => 'varchar(255)',
            'label'           => '仓库编码',
            'in_list'         => true,
            'default_in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'editable'        => false,
            'order'           => 60,
        ),
        'pay_type'          => array(
            'type'            => 'number',
            'label'           => '支付类型',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 70,
        ),
        'self_reference'    => array(
            'type'            => 'number',
            'label'           => '是否自提',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 70,
        ),
        'is_store_delivery' => array(
            'type'            => 'number',
            'label'           => '是否门店退供',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 70,
        ),
        'return_type'       => array(
            'type'            => 'number',
            'label'           => '退供类型',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 80,
        ),
        'out_time'          => array(
            'type'            => 'time',
            'label'           => '出仓时间',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 90,
            'filtertype' => 'time',
            'filterdefault' => true,
        ),
        'create_time'       => array(
            'type'            => 'time',
            'label'           => '创建时间',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 100,
        ),
        'last_modified'=>array(
            'type' => 'last_modify',
            'editable' => false,
            'in_list' => true,
            'label'=>'最后更新时间',
            'default_in_list' => true,
        ),
        'posted_time'       => array(
            'type'            => 'time',
            'label'           => '明细发布时间',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 101,
        ),
        'return_address_no' => array(
            'type'            => 'varchar(255)',
            'label'           => '供应商退供地址编码',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 110,
        ),
        'consignee'         => array(
            'type'            => 'varchar(255)',
            'label'           => '退供收货人',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 120,
        ),
        'mobile'            => array(
            'type'            => 'varchar(255)',
            'label'           => '移动电话',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 130,
        ),
        'telephone'         => array(
            'type'            => 'varchar(255)',
            'label'           => '座机',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 140,
        ),
        'address'           => array(
            'type'            => 'varchar(255)',
            'label'           => '收货地址',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 150,
        ),
        'country'           => array(
            'type'            => 'varchar(255)',
            'label'           => '国家标识',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 160,
        ),
        'state'             => array(
            'type'            => 'varchar(255)',
            'label'           => '省/州',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 160,
        ),
        'city'              => array(
            'type'            => 'varchar(255)',
            'label'           => '城市',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 170,
        ),
        'region'            => array(
            'type'            => 'varchar(255)',
            'label'           => '区/县',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 180,
        ),
        'town'              => array(
            'type'            => 'varchar(255)',
            'label'           => '乡镇/街道',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 190,
        ),
        'postcode'          => array(
            'type'            => 'varchar(255)',
            'label'           => '邮政编码',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
                        'order'           => 200,
        ),
        'to_email'          => array(
            'type'            => 'varchar(255)',
            'label'           => '退供通知email地址',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 210,
        ),
        'cc_email'          => array(
            'type'            => 'varchar(255)',
            'label'           => '退供抄送email地址',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 220,
        ),
        'logi_no'       =>array(

            'type'            => 'varchar(50)',
            'label'           => '运单号',
            'searchtype' => 'nequal',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 220,
            'filtertype' => 'yes',
            'filterdefault' => true,
        ),
        'logi_name' =>array(
            'type'            => 'varchar(50)',
            'label'           => '快递公司名称',
            'in_list'         => true,
            'default_in_list' => true,
     
        ),
        'packagestatusname'=>array(
            'type'            => 'varchar(50)',
            'label'           => '运单状态',
            'in_list'         => true,
            'default_in_list' => true,
  
        ),
        'storeid'=>array(
            'type'            => 'varchar(50)',
            'label'           => '备件库Id',
            'in_list'         => true,
            'default_in_list' => true,
          
  
        ),
         'in_branch_id' => array (
            'type' => 'table:branch@ome',
            'editable' => false,
            'label' => '入库仓库',
            'width' => 110,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 39,
        ),

        'iostock_time' => array(
            'type'            => 'time',
            'label'           => '入库时间',
            'in_list'         => true,
            'default_in_list' => true,
            'editable'        => false,
            'order'           => 100,
             'filtertype'    => 'time',
            'filterdefault' => true,
            'in_list'       => true,
        ),
        'bill_status' => array(
            'type' => array(
                '0' => '未读取',
                '1' => '待读取',
                '2' => '已读取',
                '5' => '无需读取', 
            ),

            'default' => '0',
            'label' => '读取状态',
            'in_list'         => true,
            'default_in_list' => true,
            'editable' => false,
            'filtertype' => 'yes',
            'filterdefault' => true,
        ),

    ),
    'index'   => array(
        'ind_return_sn' => array('columns' => array('return_sn'), 'prefix' => 'unique'),
        'ind_logi_no' => array('columns' => array('logi_no')),
        'ind_status' => array('columns' => array('status')),
        'ind_iostock_time' => array('columns' => array('iostock_time')),
        'ind_bill_status' => array('columns' => array('bill_status')),
    ),
    'comment' => '唯品会退货单',
    'engine'  => 'innodb',
    'version' => '$Rev: 40654 $',
);
