<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['wms_transferorder'] = array(
    'columns' => array(
        'id'        => array(
            'type'     => 'int unsigned',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'label'    => 'ID',
            'width'    => 110,
            'hidden'   => true,
            'editable' => false,
        ),
        'stockdump_id' => array(
            'type' => 'table:stockdump@console',
            'label' => 'OMS转储单ID'
        ),
        'order_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => '转储单号',
            'default_in_list' => true,
            'searchtype'      => 'nequal',
            'in_list'         => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'order' => 10,
            'width'           => 200,
        ),
        'stockdump_status'        => array(
            'type'            => [
                '1' => '未完成',
                '2' => '已完成',
            ],
            'label'           => '转储单状态',
            'default'         => '1',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'order' => 15,
            'width'           => 200,
        ),
        'erp_order_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => 'erp_order_code',
            'default_in_list' => true,
            'searchtype'      => 'nequal',
            'in_list'         => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'order' => 20,
            'width'           => 200,
        ),
        'wms_status'        => array(
            'type'            => 'varchar(255)',
            'label'           => '第三方状态',
            'default'         => '',
            'width'           => 200,
        ),
        'wms_node_id'        => array(
            'type'            => 'varchar(255)',
            'label'           => '第三方仓储绑定ID',
            'default'         => '',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 30,
            'width'           => 200,
        ),
        'out_order_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => '出库单号',
            'default'         => '',
            'default_in_list' => true,
            'order' => 35,
            'width'           => 200,
        ),
        'in_order_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => '入库单号',
            'default'         => '',
            'default_in_list' => true,
            'order' => 35,
            'width'           => 200,
        ),
        'out_confirm_time'        => array(
            'type'            => 'varchar(25)',
            'label'           => '确认出库时间',
            'default'         => '',
            'default_in_list' => true,
            'order' => 35,
            'width'           => 200,
        ),
        'in_confirm_time'        => array(
            'type'            => 'varchar(25)',
            'label'           => '确认入库时间',
            'default'         => '',
            'default_in_list' => true,
            'order' => 35,
            'width'           => 200,
        ),
        'create_time'        => array(
            'type'            => 'varchar(25)',
            'label'           => '创建时间',
            'default'         => '',
            'default_in_list' => true,
            'order' => 45,
            'width'           => 200,
        ),
        'extend_props'        => array(
            'type'            => 'text',
            'label'           => '扩展属性',
            'order' => 75,
            'width'           => 200,
        ),
        'from_warehouse_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => '转储出库仓编码',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 50,
            'width'           => 200,
        ),
        'to_warehouse_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => '转储入库仓编码',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 50,
            'width'           => 200,
        ),
        'owner_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => '货主编码',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 60,
            'width'           => 200,
        ),
        'order_status'        => array(
            'type'            => 'varchar(255)',
            'label'           => '单据状态',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 65,
            'width'           => 200,
        ),
        'at_time'       => array(
            'type'            => 'TIMESTAMP',
            'label'           => '创建时间',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'time',
            'filterdefault'   => true,
            'default'         => 'CURRENT_TIMESTAMP',
            'order' => 100,
        ),
        'up_time'       => array(
            'type'            => 'TIMESTAMP',
            'label'           => '更新时间',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'time',
            'filterdefault'   => true,
            'default'         => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'order' => 110,
        ),
    ),
    'index'   => array(
        'idx_order_code_erp_order_code_wms_node_id'   => array('columns' => array('order_code','erp_order_code','wms_node_id'), 'prefix' => 'UNIQUE'),
        'idx_erp_order_code'     => array('columns' => array('erp_order_code')),
        'idx_at_time'     => array('columns' => array('at_time')),
        'idx_up_time'     => array('columns' => array('up_time')),
    ),
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
    'comment' => '第三方转储单',
);
