<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['wms_storeprocess'] = array(
    'columns' => array(
        'id'        => array(
            'type'     => 'int unsigned',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'label'    => 'ID',
            'width'    => 110,
            'hidden'   => true,
            'editable' => false,
        ),
        'mp_id' => array(
            'type' => 'table:material_package@console',
            'label' => 'OMS出入单ID'
        ),
        'mp_bn'        => array(
            'type'            => 'varchar(255)',
            'label'           => '加工单号',
            'default_in_list' => true,
            'searchtype'      => 'nequal',
            'in_list'         => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'order' => 10,
            'width'           => 200,
        ),
        'mp_status'        => array(
            'type'            => [
                '1' => '未完成',
                '2' => '已完成',
            ],
            'label'           => '加工单状态',
            'default'         => '1',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'order' => 15,
            'width'           => 200,
        ),
        'process_order_id'        => array(
            'type'            => 'varchar(255)',
            'label'           => '仓储系统加工单ID',
            'default_in_list' => true,
            'searchtype'      => 'nequal',
            'in_list'         => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'order' => 20,
            'width'           => 200,
        ),
        'wms_node_id'        => array(
            'type'            => 'varchar(255)',
            'label'           => '第三方仓储绑定ID',
            'default'         => '',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 30,
            'width'           => 200,
        ),
        'order_type'        => array(
            'type'            => 'varchar(255)',
            'label'           => '单据类型',
            'default'         => '',
            'default_in_list' => true,
            'order' => 35,
            'width'           => 200,
        ),
        'order_complete_time'        => array(
            'type'            => 'varchar(25)',
            'label'           => '加工单完成时间',
            'default'         => '',
            'default_in_list' => true,
            'order' => 35,
            'width'           => 200,
        ),
        'actual_qty'        => array(
            'type'            => 'varchar(25)',
            'label'           => '实际作业总数量',
            'default'         => '',
            'default_in_list' => true,
            'order' => 35,
            'width'           => 200,
        ),
        'remark'        => array(
            'type'            => 'text',
            'label'           => '备注',
            'default'         => '',
            'default_in_list' => true,
            'order' => 45,
            'width'           => 200,
        ),
        'extend_props'        => array(
            'type'            => 'text',
            'label'           => '扩展属性',
            'order' => 35,
            'width'           => 200,
        ),
        'warehouse_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => '仓库编码',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 50,
            'width'           => 200,
        ),
        'at_time'       => array(
            'type'            => 'TIMESTAMP',
            'label'           => '创建时间',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'time',
            'filterdefault'   => true,
            'default'         => 'CURRENT_TIMESTAMP',
            'order' => 100,
        ),
        'up_time'       => array(
            'type'            => 'TIMESTAMP',
            'label'           => '更新时间',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'time',
            'filterdefault'   => true,
            'default'         => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'order' => 110,
        ),
    ),
    'index'   => array(
        'idx_mp_bn_process_order_id_wms_node_id'   => array('columns' => array('mp_bn','process_order_id','wms_node_id'), 'prefix' => 'UNIQUE'),
        'idx_process_order_id'     => array('columns' => array('process_order_id')),
        'idx_at_time'     => array('columns' => array('at_time')),
        'idx_up_time'     => array('columns' => array('up_time')),
    ),
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
    'comment' => '第三方加工单',
);
