<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['wms_stock_change'] = array(
    'columns' => array(
        'id'        => array(
            'type'     => 'int unsigned',
            'required' => true,
            'pkey'     => true,
            'extra'    => 'auto_increment',
            'label'    => 'ID',
            'width'    => 110,
            'hidden'   => true,
            'editable' => false,
        ),
        'unique_bn'        => array(
            'type'            => 'varchar(255)',
            'label'           => '异动单号',
            'default_in_list' => true,
            'searchtype'      => 'nequal',
            'in_list'         => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'order' => 10,
            'width'           => 200,
        ),
        'adjust_status'        => array(
            'type'            => [
                '1' => '未调整',
                '2' => '调整完成',
            ],
            'label'           => '调整单状态',
            'default'         => '1',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'order' => 15,
            'width'           => 200,
        ),
        'adjust_msg'        => array(
            'type'            => 'varchar(255)',
            'label'           => '调整信息',
            'default'         => '',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 15,
            'width'           => 500,
        ),
        'order_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => '引起异动的单据编码',
            'default_in_list' => true,
            'searchtype'      => 'nequal',
            'in_list'         => true,
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'order' => 20,
            'width'           => 200,
        ),
        'order_type'        => array(
            'type'            => 'varchar(255)',
            'label'           => '单据类型',
            'default'         => '',
            'width'           => 200,
        ),
        'wms_node_id'        => array(
            'type'            => 'varchar(255)',
            'label'           => '第三方仓储绑定ID',
            'default'         => '',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 30,
            'width'           => 200,
        ),
        'batch_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => '批次编号',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'default'         => '',
            'default_in_list' => true,
            'in_list'         => true,
            'order' => 35,
            'width'           => 200,
        ),
        'warehouse'        => array(
            'type'            => 'varchar(255)',
            'label'           => '仓库编码',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'normal',
            'order' => 40,
            'width'           => 200,
        ),
        'product_bn'        => array(
            'type'            => 'varchar(255)',
            'label'           => '基础物料编码',
            'default'         => '',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 45,
            'width'           => 200,
        ),
        'normal_num'        => array(
            'type'            => 'mediumint',
            'label'           => '良品数量',
            'default'         => 0,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 50,
            'width'           => 200,
        ),
        'defective_num'        => array(
            'type'            => 'mediumint',
            'label'           => '不良品数量',
            'default'         => 0,
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 55,
            'width'           => 200,
        ),
        'wms_item_id'        => array(
            'type'            => 'varchar(255)',
            'label'           => '仓储物料ID',
            'filtertype'      => 'normal',
            'filterdefault'   => true,
            'default'         => '',
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 60,
            'width'           => 200,
        ),
        'change_time'        => array(
            'type'            => 'TIMESTAMP',
            'label'           => '异动时间',
            'default'         => 'CURRENT_TIMESTAMP',
            'in_list'         => true,
            'default_in_list' => true,
            'filtertype'      => 'time',
            'filterdefault'   => true,
            'order' => 65,
            'width'           => 200,
        ),
        'expire_date'        => array(
            'type'            => 'varchar(24)',
            'label'           => '商品过期日期',
            'default'         => '',
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 70,
            'width'           => 200,
        ),
        'product_date'        => array(
            'type'            => 'varchar(24)',
            'label'           => '商品生产日期',
            'default'         => '',
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 75,
            'width'           => 200,
        ),
        'produce_code'        => array(
            'type'            => 'varchar(255)',
            'label'           => '生产批号',
            'default'         => '',
            'in_list'         => true,
            'default_in_list' => true,
            'order' => 80,
            'width'           => 200,
        ),
        'sn_list'        => array(
            'type'            => 'text',
            'label'           => '唯一码',
            'default'         => '',
            'order' => 80,
            'width'           => 200,
        ),
        'at_time'       => array(
            'type'            => 'TIMESTAMP',
            'label'           => '创建时间',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'time',
            'filterdefault'   => true,
            'default'         => 'CURRENT_TIMESTAMP',
            'order' => 100,
        ),
        'up_time'       => array(
            'type'            => 'TIMESTAMP',
            'label'           => '更新时间',
            'default_in_list' => true,
            'in_list'         => true,
            'filtertype'      => 'time',
            'filterdefault'   => true,
            'default'         => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'order' => 110,
        ),
    ),
    'index'   => array(
        'idx_unique_bn'   => array('columns' => array('unique_bn'), 'prefix' => 'UNIQUE'),
        'idx_order_code'  => array('columns' => array('order_code')),
        'idx_product_bn'  => array('columns' => array('product_bn')),
        'idx_wms_item_id' => array('columns' => array('wms_item_id')),
        'idx_batch_code'  => array('columns' => array('batch_code')),
        'idx_change_time' => array('columns' => array('change_time')),
        'idx_at_time'     => array('columns' => array('at_time')),
        'idx_up_time'     => array('columns' => array('up_time')),
    ),
    'engine'  => 'innodb',
    'version' => '$Rev:  $',
    'comment' => '第三方库存异动单',
);
