<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

/**
 * @author ykm 2018/4/12
 * @describe 售后数据转换
 */

class erpapi_shop_matrix_shunguang_response_aftersalev2 extends erpapi_shop_response_aftersalev2 {

    protected function _getAddType($sdf) {
        if (in_array($sdf['order']['ship_status'],array('0'))) {
            #有退货，未发货的,做退款
            return 'refund';
        }else{
            #有退货，已发货的,做售后
            return 'returnProduct';
        }
    }

    protected function _formatAddParams($params) {
        $sdf = parent::_formatAddParams($params); // TODO: Change the autogenerated stub
        $sdf['refund_type'] = 'apply';
        return $sdf;
    }


    protected function _formatAddItemList($sdf, $convert=array()) {
        $convert = array(
            'sdf_field'=>'oid',
            'order_field'=>'oid',
            'default_field'=>'item_id'
        );
        return parent::_formatAddItemList($sdf, $convert);
    }

}