<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['account_settlement'] = array(
    'columns' => array(
        'sid' => array(
            'pkey' => 'true',
            'type' => 'int unsigned',
            'extra' => 'auto_increment',
            'label' => '序号',
            'order' => 1,
        ),
        'shop_id' => array(
            'type' => 'table:shop@ome',
            'label' => '店铺',
            'in_list'         => true,
            'default_in_list' => true,
            'editable' => false,
        ),
        'shqid' => array(
            'type' => 'varchar(32)',
            'label' => '结算单号',
            'editable' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'searchtype' => 'nequal',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 10,
        ),
        'paymentOrder' => array(
            'type' => 'varchar(32)',
            'label' => '支付单号',
            'editable' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'searchtype' => 'nequal',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 90,
        ),
        'confirmStatus' => array(
            'type' => 'varchar(32)',
            'label' => '确认状态',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 23,
        ),
        'approveStatus' => array(
            'type' => array(
                '101' => '待审核',
                '103' => '审核通过',
                '104' => '审核驳回',
                '205' => '未驳回',
            ),
            'label' => '审核状态',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 20,
        ),
        'summoney' => array(
            'type' => 'decimal(20,3)',
            'label' => '应结金额',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 22,
        ),
        'payMoney' => array(
            'type' => 'decimal(20,3)',
            'label' => '应付金额',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 24,
        ),
        'pattern' => array(
            'type' => 'number',
            'label' => '结算模式',
            'editable' => true,
            'default' => 0,
            'width' => 90,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 22,
        ),
        'operatorName' => array(
            'type' => 'varchar(32)',
            'label' => '结算员',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 30,
        ),
        'vendorCode' => array(
            'type' => 'varchar(32)',
            'label' => '供应商简码',
            'editable' => true,
            'filtertype' => 'normal',
            'filterdefault' => 'true',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 32,
        ),
        'paycompanyid' => array(
            'type' => 'number',
            'label' => '合同主体id',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 34,
        ),
        'isscf' => array(
            'type' => 'varchar(32)',
            'label' => '是否保理业务',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 36,
        ),
        'approvedpaydate' => array(
            'type' => 'varchar(32)',
            'label' => '核定付款日期',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 40,
        ),
        'settlementStatus' => array(
            'type' => 'number',
            'label' => '供应商结算状态',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 42,
        ),
        'fileUrl' => array(
            'type' => 'varchar(255)',
            'label' => '文件URL',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'width' => 380,
            'order' => 50,
        ),
        'file_status' => array(
            'type' => array(
                'none' => '未下载',
                'download' => '已下载',
                'download_fail' => '下载失败',
                'unzip' => '已解压',
                'unzip_fail' => '解压失败',
                'analysis' => '已解析',
                'analysis_fail' => '解析失败',
            ),
            'default' => 'none',
            'label' => '文件状态',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 51,
        ),
        'localUrl' => array(
            'type' => 'varchar(255)',
            'label' => '本地文件URL',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'width' => 380,
            'order' => 53,
        ),
        'unzipUrl' => array(
            'type' => 'varchar(255)',
            'label' => '解压文件URL',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'width' => 380,
            'order' => 55,
        ),
        'requestorName' => array(
            'type' => 'varchar(32)',
            'label' => '采销员姓名',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 52,
        ),
        'planpaydate' => array(
            'type' => 'varchar(32)',
            'label' => '预计付款日期',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 54,
        ),
        'rejectCause' => array(
            'type' => 'varchar(80)',
            'label' => '驳回原因',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 58,
        ),
        'createDate' => array (
            'type' => 'time',
            'editable' => false,
            'label' => '结算单创建时间',
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 92,
        ),
        'receiveMoney' => array(
            'type' => 'decimal(20,3)',
            'label' => '应收金额',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 60,
        ),
        'channelCode' => array(
            'type' => 'varchar(32)',
            'label' => '渠道编码',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 70,
        ),
        'billingAmount' => array(
            'type' => 'decimal(20,3)',
            'label' => '应开票金额',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 80,
        ),
        'paytime' => array (
            'type' => 'time',
            'editable' => false,
            'label' => '付款日期',
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 94,
        ),
        'vendorName' => array(
            'type' => 'varchar(32)',
            'label' => '供应商名称',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 72,
        ),
        'openInvoiceStatus' => array(
            'type' => 'number',
            'label' => '待开票状态',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 74,
        ),
        'paycompany' => array(
            'type' => 'varchar(32)',
            'label' => '合同主体名称',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 82,
        ),
        'hxstatus' => array(
            'type' => 'varchar(32)',
            'label' => '核销状态',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 84,
        ),
        'addType' => array(
            'type' => 'number',
            'label' => '出单方式',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 86,
        ),
        'requestorId' => array(
            'type' => 'varchar(32)',
            'label' => '采销员id',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 75,
        ),
        'channelName' => array(
            'type' => 'varchar(32)',
            'label' => '渠道名称',
            'editable' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 76,
        ),
        'payStatus' => array(
            'type' => 'varchar(32)',
            'label' => '付款状态',
            'editable' => true,
            'in_list' => false,
            'default_in_list' => false,
            'order' => 78,
        ),
        'error_msg' => array (
            'type' => 'text',
            'label' => '失败原因',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            'width' => 380,
            'order' => 55,
        ),
        'create_time' => array (
            'type' => 'time',
            'editable' => false,
            'label' => '创建时间',
            'filtertype' => 'time',
            'filterdefault' => true,
            'in_list' => true,
            'default_in_list' => true,
            'order' => 98,
        ),
        'last_modified' => array (
            'type' => 'time',
            'editable' => false,
            'label' => '最后修改时间',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 99,
        ),
    ),
    'index' => array(
        'ind_shqid' => array(
            'columns' => array(
                0 => 'shqid',
            ),
            'prefix' => 'unique',
        ),
        'ind_paymentOrder' => array(
            'columns' => array(
                0 => 'paymentOrder',
            ),
        ),
        'ind_channelCode' => array(
            'columns' => array(
                0 => 'channelCode',
            ),
        ),
        'ind_createDate' => array(
            'columns' => array(
                0 => 'createDate',
            ),
        ),
        'ind_create_time' => array(
            'columns' => array(
                0 => 'create_time',
            ),
        ),
        'ind_file_status' => array(
            'columns' => array(
                0 => 'file_status',
            ),
        ),
    ),
    'engine' => 'innodb',
    'version' => '$Rev: $',
    'comment' => '结算单表',
);