<?php
/**
 * Copyright © ShopeX （http://www.shopex.cn）. All rights reserved.
 * See LICENSE file for license details.
 */

$db['vreturn_diff']=[
    'columns' => [
        'id' => [
            'type' => 'int unsigned',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
            'editable' => false,
            'order' => 1,
        ],
        'rv_difference_no' => [
            'type' => 'varchar(32)',
            'label' => '差异单号',
            'in_list' => true,
            'default_in_list' => true,
            'searchtype'      => 'nequal',
            'filtertype' => 'normal',
            'filterdefault' => true,
            'required' => true,
            'order' => 10,
        ],
        'status_name' => [
            'type' => 'varchar(32)',
            'label' => '状态',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 20,
        ],
        'sub_return_no' => [
            'type' => 'varchar(32)',
            'label' => '子单号',
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'order' => 30,
        ],
        'return_no' => [
            'type' => 'varchar(32)',
            'label' => '退供单号',
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'order' => 40,
        ],
        'po_no' => [
            'type' => 'varchar(32)',
            'label' => 'PO号',
            'in_list' => true,
            'default_in_list' => true,
            'filtertype' => 'normal',
            'filterdefault' => true,
            'searchtype'      => 'nequal',
            'order' => 50,
        ],
        'schedule_id' => [
            'type' => 'varchar(32)',
            'label' => '档期ID',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 60,
        ],
        'poDelivery_type_name' => [
            'type' => 'varchar(32)',
            'label' => '发货类型',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 70,
        ],
        'create_time_str' => [
            'type' => 'varchar(25)',
            'label' => '差异单创建时间',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 80,
        ],
        'update_time_str' => [
            'type' => 'varchar(25)',
            'label' => '差异单更新时间',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 90,
        ],
        'contractor' => [
            'type' => 'varchar(255)',
            'label' => '联系人名称',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 100,
        ],
        'telephone' => [
            'type' => 'varchar(200)',
            'label' => '联系人电话',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 110,
        ],
        'follow_up_department' => [
            'type' => 'varchar(100)',
            'label' => '跟进人部门',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 120,
        ],
        'follow_up_name' => [
            'type' => 'varchar(100)',
            'label' => '跟进人名称',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 130,
        ],
        'step_back_po' => [
            'type' => 'varchar(255)',
            'label' => '回采PO',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 140,
        ],
        'ebs_bill_number' => [
            'type' => 'varchar(50)',
            'label' => '财务账单',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 150,
        ],
        'step_back_transport_no' => [
            'type' => 'varchar(32)',
            'label' => '回采运单号',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 160,
        ],
        'required_transport_no' => [
            'type' => 'int',
            'label' => '回采运单号是否必填',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 170,
        ],
        'warehouse_name' => [
            'type' => 'varchar(200)',
            'label' => '仓库名称',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 180,
        ],
        'return_type_name' => [
            'type' => 'varchar(32)',
            'label' => '退供类型名称',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 190,
        ],
        'status' => [
            'type' => 'int',
            'label' => '状态',
        ],
        'status_note' => [
            'type' => 'text',
            'label' => '备注',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 200,
        ],
        'is_complete' => [
            'type' => 'tinyint(1)',
            'label' => '是否完整',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 210,
        ],
        'approve_qty' => [
            'type' => 'int',
            'label' => '通过行总数',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 220,
        ],
        'not_approve_qty' => [
            'type' => 'int',
            'label' => '未通过行总数',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 230,
        ],
        'is_download_finished' => [
            'type' => [
                '0' => '否',
                '1' => '是',
            ],
            'label' => '是否下载完成',
            'in_list' => true,
            'default' => '1',
            'filtertype' => 'normal',
            'order' => 240,
        ],
        'download_msg' => [
            'type' => 'text',
            'label' => '下载失败原因',
            'in_list' => true,
            'order' => 250,
        ],
        'return_price_discount' => [
            'type' => 'decimal(20,8)',
            'label' => '确认赔偿折扣',
            'default' => '0',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 260,
        ],
        'return_diff_amount' => [
            'type' => 'money',
            'label' => '结算总额',
            'default' => '0',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 270,
        ],
        'record_quantity' => [
            'type' => 'int',
            'label' => '退供数',
            'default' => '0',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 280,
        ],
        'real_quantity' => [
            'type' => 'int',
            'label' => '实收数',
            'default' => '0',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 290,
        ],
        'diff_quantity' => [
            'type' => 'int',
            'label' => '差异数',
            'default' => '0',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 300,
        ],
        'pay_quantity' => [
            'type' => 'int',
            'label' => '赔偿数',
            'default' => '0',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 310,
        ],
        'diff_amount' => [
            'type' => 'decimal(20,8)',
            'label' => '差异金额',
            'default' => '0',
            'in_list' => true,
            'default_in_list' => true,
            'order' => 320,
        ],
        'shop_id' => [
            'type' => 'varchar(32)',
            'label' => '来源店铺',
            'in_list' => true,
            'default_in_list' => true,
        ],
        'at_time'           => [
            'type'    => 'TIMESTAMP',
            'label'   => '创建时间',
            'default' => 'CURRENT_TIMESTAMP',
            'width'           => 130,
            'in_list' => true,
            'order' => 330,
        ],
        'up_time'           => [
            'type'    => 'TIMESTAMP',
            'label'   => '更新时间',
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'width'           => 130,
            'in_list' => true,
            'order' => 340,
        ],
        'in_sale' => [
            'type'    => [
                '0' => '未进',
                '1' => '处理中',
                '2' => '已进',
            ],
            'label'   => '生成销售单',
            'default' => '0',
            'in_list' => true,
            'order' => 350,
        ],
        'in_sale_errmsg' => [
            'type'    => 'text',
            'label'   => '销售单失败原因',
            'in_list' => true,
            'order' => 360,
        ],
    ],
    'index' => [
        'ind_at_time' => ['columns' => ['at_time']],
        'ind_up_time' => ['columns' => ['up_time']],
        'ind_rv_difference_no' => ['columns' => ['rv_difference_no','shop_id'], 'prefix' => 'unique'],
        'ind_sub_return_no' => ['columns' => ['sub_return_no']],
        'ind_return_no' => ['columns' => ['return_no']],
        'ind_po_no' => ['columns' => ['po_no']],
        'ind_shop_id' => ['columns' => ['shop_id']],
        'ind_in_sale' => ['columns' => ['in_sale']],
    ],
    'comment' => '退供差异账单',
    'engine' => 'innodb',
    'version' => '$Rev: $',
];
